//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{serde::ts_seconds, DateTime, Utc};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromQueryResult, IntoActiveModel, JoinType, QueryOrder,
    QuerySelect,
};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use super::{challenge, team, user};

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum State {
    #[default]
    Pending = 0,
    Misjudged = 1,
    Confirmed = 2,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "audit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(with = "ts_seconds")]
    pub created_at: DateTime<Utc>,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub challenge_id: i64,
    pub user_id: i64,
    pub team_id: i64,
    pub game_id: i64,
    pub state: State,
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
    pub id: i64,
    #[serde(with = "ts_seconds")]
    pub created_at: DateTime<Utc>,
    pub reason: String,
    pub challenge_id: i64,
    pub challenge_name: String,
    pub user_id: i64,
    pub user_name: String,
    pub team_id: i64,
    pub team_name: String,
    pub game_id: i64,
    pub game_name: String,
    pub state: State,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Team,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_page(
    db: &DatabaseConnection, page: u64, page_size: u64, game_id: Option<i64>, team_id: Option<i64>,
    user_id: Option<i64>, challenge_id: Option<i64>, state: Option<State>,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find();
    if let Some(game_id) = game_id {
        sql = sql.filter(Column::GameId.eq(game_id));
    }
    if let Some(team_id) = team_id {
        sql = sql.filter(Column::TeamId.eq(team_id));
    }
    if let Some(user_id) = user_id {
        sql = sql.filter(Column::UserId.eq(user_id));
    }
    if let Some(challenge_id) = challenge_id {
        sql = sql.filter(Column::ChallengeId.eq(challenge_id));
    }
    if let Some(state) = state {
        sql = sql.filter(Column::State.eq(state));
    }
    let paginator = sql
        .order_by_desc(Column::CreatedAt)
        .into_model()
        .paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let articles = paginator.fetch_page(page - 1).await?;
    Ok((articles, total))
}

pub async fn get_page_ex(
    db: &DatabaseConnection, page: u64, page_size: u64, game_id: Option<i64>, team_id: Option<i64>,
    user_id: Option<i64>, challenge_id: Option<i64>, state: Option<State>,
) -> Result<(Vec<ExModel>, u64), DbErr> {
    let mut sql = Entity::find()
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .join(JoinType::InnerJoin, Relation::Team.def())
        .join(JoinType::InnerJoin, Relation::User.def())
        .column_as(challenge::Column::Name, "challenge_name")
        .column_as(team::Column::Name, "team_name")
        .column_as(user::Column::Nickname, "user_name");
    if let Some(game_id) = game_id {
        sql = sql.filter(Column::GameId.eq(game_id));
    }
    if let Some(team_id) = team_id {
        sql = sql.filter(Column::TeamId.eq(team_id));
    }
    if let Some(user_id) = user_id {
        sql = sql.filter(Column::UserId.eq(user_id));
    }
    if let Some(challenge_id) = challenge_id {
        sql = sql.filter(Column::ChallengeId.eq(challenge_id));
    }
    if let Some(state) = state {
        sql = sql.filter(Column::State.eq(state));
    }
    let paginator = sql
        .order_by_desc(Column::CreatedAt)
        .into_model()
        .paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let articles = paginator.fetch_page(page - 1).await?;
    Ok((articles, total))
}

pub async fn create(db: &DatabaseConnection, model: Model) -> Result<Model, DbErr> {
    let model = ActiveModel {
        id: ActiveValue::NotSet,
        created_at: ActiveValue::Set(Utc::now()),
        ..model.into_active_model().reset_all()
    };
    model.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
