//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use std::collections::HashSet;

use chrono::{DateTime, Utc, serde::ts_seconds};
use sea_orm::{ActiveValue, IntoActiveModel, QueryOrder, entity::prelude::*};
use serde::{Deserialize, Serialize};
use validator::Validate;

use crate::{challenge::PrerequisiteList, validation::non_blank};

/// A game-scoped milestone: when a team has solved every challenge listed in
/// `prerequisites`, the static `bonus_score` is awarded on top of the regular
/// challenge and extra scores.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Validate)]
#[sea_orm(table_name = "challenge_milestone")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[serde(with = "ts_seconds")]
  pub created_at: DateTime<Utc>,
  #[serde(with = "ts_seconds")]
  pub updated_at: DateTime<Utc>,
  pub game_id: i64,
  #[sea_orm(column_type = "JsonBinary")]
  #[serde(default = "PrerequisiteList::default")]
  pub prerequisites: PrerequisiteList,
  #[serde(default = "Option::default")]
  #[validate(length(
    max = "crate::validation::AVATAR_MAX_LEN",
    message = "milestone avatar must be at most 255 characters"
  ))]
  pub avatar: Option<String>,
  #[validate(range(
    min = 0,
    max = 10000,
    message = "milestone bonus score must be between 0 and 10000"
  ))]
  pub bonus_score: i32,
  #[validate(
    custom(function = "non_blank", message = "milestone name is required"),
    length(max = 127, message = "milestone name must be at most 127 characters")
  )]
  pub name: String,
  #[sea_orm(column_type = "Text")]
  #[validate(custom(function = "non_blank", message = "milestone description is required"))]
  pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::game::Entity",
    from = "Column::GameId",
    to = "super::game::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  Game,
}

impl Related<super::game::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Game.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C, id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(id).one(db).await
}

pub async fn get_list<C>(db: &C, game_id: i64) -> Result<Vec<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find()
    .filter(Column::GameId.eq(game_id))
    .order_by_asc(Column::Id)
    .all(db)
    .await
}

pub async fn create<C>(db: &C, milestone: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let milestone = ActiveModel {
    id: ActiveValue::NotSet,
    created_at: ActiveValue::Set(Utc::now()),
    updated_at: ActiveValue::Set(Utc::now()),
    ..milestone.into_active_model().reset_all()
  };
  milestone.insert(db).await
}

pub async fn update<C>(db: &C, milestone: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let milestone = ActiveModel {
    id: ActiveValue::Unchanged(milestone.id),
    game_id: ActiveValue::NotSet,
    created_at: ActiveValue::NotSet,
    updated_at: ActiveValue::Set(Utc::now()),
    ..milestone.into_active_model().reset_all()
  };
  milestone.update(db).await
}

pub async fn delete<C>(db: &C, id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_by_id(id).exec(db).await.map(|_| ())
}

pub async fn delete_by_game_id<C>(db: &C, game_id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_many()
    .filter(Column::GameId.eq(game_id))
    .exec(db)
    .await
    .map(|_| ())
}

/// Whether another milestone of the same game already uses the given name.
pub async fn is_name_taken<C>(
  db: &C, game_id: i64, exclude_id: Option<i64>, name: &str,
) -> Result<bool, DbErr>
where
  C: ConnectionTrait, {
  let mut query = Entity::find()
    .filter(Column::GameId.eq(game_id))
    .filter(Column::Name.eq(name));
  if let Some(id) = exclude_id {
    query = query.filter(Column::Id.ne(id));
  }
  Ok(query.count(db).await? > 0)
}

/// Evaluates the static bonus scores of all milestones that are satisfied by
/// the given set of solved challenge ids. A milestone counts as satisfied only
/// when its prerequisites are non-empty and every one of them is solved.
pub fn milestone_bonus(solved: &HashSet<i64>, milestones: &[Model]) -> i32 {
  milestones
    .iter()
    .filter(|milestone| {
      !milestone.prerequisites.0.is_empty()
        && milestone
          .prerequisites
          .0
          .iter()
          .all(|id| solved.contains(id))
    })
    .map(|milestone| milestone.bonus_score)
    .sum()
}

#[cfg(test)]
mod tests {
  use std::collections::HashSet;

  use chrono::Utc;
  use validator::Validate;

  use super::{Model, milestone_bonus};
  use crate::challenge::PrerequisiteList;

  fn milestone(id: i64, bonus_score: i32, prerequisites: Vec<i64>) -> Model {
    Model {
      id,
      created_at: Utc::now(),
      updated_at: Utc::now(),
      game_id: 1,
      prerequisites: PrerequisiteList(prerequisites),
      avatar: None,
      bonus_score,
      name: format!("milestone-{id}"),
      description: String::new(),
    }
  }

  fn valid_milestone() -> Model {
    Model {
      description: "a milestone".to_owned(),
      ..milestone(1, 100, vec![10])
    }
  }

  #[test]
  fn validation_matches_the_former_route_rules() {
    assert!(valid_milestone().validate().is_ok());
    // name: required and at most 127 characters
    assert!(
      Model {
        name: " ".to_owned(),
        ..valid_milestone()
      }
      .validate()
      .is_err()
    );
    assert!(
      Model {
        name: "a".repeat(127),
        ..valid_milestone()
      }
      .validate()
      .is_ok()
    );
    assert!(
      Model {
        name: "a".repeat(128),
        ..valid_milestone()
      }
      .validate()
      .is_err()
    );
    // description: required
    assert!(milestone(1, 100, vec![10]).validate().is_err());
    // bonus score: 0..=10000
    assert!(
      Model {
        bonus_score: -1,
        ..valid_milestone()
      }
      .validate()
      .is_err()
    );
    assert!(
      Model {
        bonus_score: 10001,
        ..valid_milestone()
      }
      .validate()
      .is_err()
    );
    // avatar: at most 255 characters when present
    assert!(
      Model {
        avatar: Some("a".repeat(255)),
        ..valid_milestone()
      }
      .validate()
      .is_ok()
    );
    assert!(
      Model {
        avatar: Some("a".repeat(256)),
        ..valid_milestone()
      }
      .validate()
      .is_err()
    );
  }

  fn solved(ids: &[i64]) -> HashSet<i64> {
    ids.iter().copied().collect()
  }

  #[test]
  fn milestone_bonus_sums_fully_satisfied_milestones() {
    let milestones = [milestone(1, 100, vec![10, 11]), milestone(2, 200, vec![20])];
    assert_eq!(milestone_bonus(&solved(&[10, 11, 20]), &milestones), 300);
  }

  #[test]
  fn milestone_bonus_skips_partially_satisfied_milestones() {
    let milestones = [milestone(1, 100, vec![10, 11])];
    assert_eq!(milestone_bonus(&solved(&[10]), &milestones), 0);
  }

  #[test]
  fn milestone_bonus_ignores_empty_prerequisites() {
    let milestones = [milestone(1, 100, vec![])];
    assert_eq!(milestone_bonus(&solved(&[10, 11]), &milestones), 0);
    assert_eq!(milestone_bonus(&solved(&[]), &milestones), 0);
  }

  #[test]
  fn milestone_bonus_is_zero_without_milestones() {
    assert_eq!(milestone_bonus(&solved(&[10]), &[]), 0);
  }
}
