//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use std::collections::HashSet;

use chrono::{
  DateTime, Utc,
  serde::{ts_seconds, ts_seconds_option},
};
use sea_orm::{
  ActiveValue, FromJsonQueryResult, IntoActiveModel, Iterable, JoinType, QueryOrder, QuerySelect,
  entity::prelude::*,
};
use serde::{Deserialize, Serialize};
use thiserror::Error as ThisError;
use validator::{Validate, ValidationError};

use super::submission;
use crate::{game, validation::non_blank};

#[derive(
  Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult, Validate,
)]
#[validate(schema(function = "minimum_not_above_initial"))]
pub struct ScoreRule {
  #[validate(range(
    min = 0,
    max = 1500,
    message = "initial score must be between 0 and 1500"
  ))]
  pub initial: i32,
  #[validate(range(
    min = 0,
    max = 1500,
    message = "minimum score must be between 0 and 1500"
  ))]
  pub minimum: i32,
  #[validate(range(min = 1, max = 200, message = "score decay must be between 1 and 200"))]
  pub decay: i32,
}

fn minimum_not_above_initial(rule: &ScoreRule) -> Result<(), ValidationError> {
  if rule.minimum > rule.initial {
    return Err(
      ValidationError::new("minimum_above_initial")
        .with_message("minimum score must not exceed initial score".into()),
    );
  }
  Ok(())
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Tag {
  name: String,
  primary: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TagList(pub Vec<Tag>);

/// Challenge ids that must be solved before this challenge can be interacted
/// with (submit, start instance, download attachment, unlock hint).
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct PrerequisiteList(pub Vec<i64>);

fn non_empty_tags(tag: &TagList) -> Result<(), ValidationError> {
  if tag.0.is_empty() {
    return Err(ValidationError::new("non_empty_tags"));
  }
  Ok(())
}

fn release_before_archive(model: &Model) -> Result<(), ValidationError> {
  if let (Some(release_at), Some(archive_at)) = (&model.release_at, &model.archive_at)
    && release_at >= archive_at
  {
    return Err(
      ValidationError::new("release_window")
        .with_message("challenge release time must be before archive time".into()),
    );
  }
  Ok(())
}

#[derive(
  Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default, Validate,
)]
#[sea_orm(table_name = "challenge")]
#[validate(schema(function = "release_before_archive"))]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[validate(custom(function = "non_blank", message = "challenge name is required"))]
  pub name: String,
  #[serde(with = "ts_seconds")]
  pub updated_at: DateTime<Utc>,
  #[sea_orm(column_type = "Text")]
  #[validate(
    required(message = "challenge content is required"),
    custom(function = "non_blank", message = "challenge content is required")
  )]
  pub content: Option<String>,
  pub hidden: bool,
  pub game_id: i64,
  #[sea_orm(column_type = "JsonBinary")]
  #[validate(custom(function = "non_empty_tags", message = "challenge tag is required"))]
  pub tag: TagList,
  #[sea_orm(column_type = "JsonBinary")]
  #[validate(nested)]
  pub score_rule: ScoreRule,
  pub score: i32,
  pub bucket: Option<String>,
  pub ref_id: Option<i64>,
  #[serde(with = "ts_seconds_option", default = "Option::default")]
  pub release_at: Option<DateTime<Utc>>,
  #[serde(with = "ts_seconds_option", default = "Option::default")]
  pub archive_at: Option<DateTime<Utc>>,
  #[sea_orm(column_type = "JsonBinary")]
  #[serde(default = "PrerequisiteList::default")]
  pub prerequisites: PrerequisiteList,
  #[serde(default = "Option::default")]
  #[validate(length(
    max = "crate::validation::AVATAR_MAX_LEN",
    message = "challenge avatar must be at most 255 characters"
  ))]
  pub avatar: Option<String>,
}

impl Model {
  pub fn desensitize(self) -> Self {
    Self {
      bucket: None,
      ..self
    }
  }
}

/// Failure modes of `resolve_prerequisites`. Domain violations are reported
/// separately from database errors so that the caller can map them to
/// different response statuses.
#[derive(Debug, ThisError)]
pub enum ResolvePrerequisitesError {
  #[error("a challenge cannot be its own prerequisite")]
  OwnPrerequisite,
  #[error("prerequisite challenge {0} does not exist")]
  NotFound(i64),
  #[error("prerequisite challenge {0} does not belong to this game")]
  WrongGame(i64),
  #[error(transparent)]
  Db(#[from] DbErr),
}

/// Resolves prerequisite ids to their challenge models. Fails when an id is
/// the excluded challenge itself, does not exist, or belongs to another game.
pub async fn resolve_prerequisites<C>(
  db: &C, game_id: i64, exclude_id: Option<i64>, prerequisites: &PrerequisiteList,
) -> Result<Vec<Model>, ResolvePrerequisitesError>
where
  C: ConnectionTrait, {
  let mut models = Vec::with_capacity(prerequisites.0.len());
  for &id in &prerequisites.0 {
    if Some(id) == exclude_id {
      return Err(ResolvePrerequisitesError::OwnPrerequisite);
    }
    let model = get(db, id)
      .await?
      .ok_or(ResolvePrerequisitesError::NotFound(id))?;
    if model.game_id != game_id {
      return Err(ResolvePrerequisitesError::WrongGame(id));
    }
    models.push(model);
  }
  Ok(models)
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::audit::Entity")]
  Audit,
  #[sea_orm(has_many = "super::extra::Entity")]
  Extra,
  #[sea_orm(
    belongs_to = "super::game::Entity",
    from = "Column::GameId",
    to = "super::game::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  Game,
  #[sea_orm(has_many = "super::hint::Entity")]
  Hint,
  #[sea_orm(has_many = "super::submission::Entity")]
  Submission,
  #[sea_orm(belongs_to = "Entity", from = "Column::RefId", to = "Column::Id")]
  Original,
}

impl Related<super::audit::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Audit.def()
  }
}

impl Related<super::extra::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Extra.def()
  }
}

impl Related<super::game::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Game.def()
  }
}

impl Related<super::hint::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Hint.def()
  }
}

impl Related<super::submission::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Submission.def()
  }
}

pub struct OriginalLink;

impl Linked for OriginalLink {
  type FromEntity = Entity;

  type ToEntity = Entity;

  fn link(&self) -> Vec<RelationDef> {
    vec![Relation::Original.def()]
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C, id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(id).one(db).await
}

pub async fn get_page<C>(
  db: &C, page: u64, page_size: u64, game_id: i64, with_hidden: bool,
) -> Result<(Vec<Model>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let mut sql = Entity::find()
    .filter(Column::GameId.eq(game_id))
    .select_only()
    .columns(Column::iter().filter(|c| !matches!(c, Column::Content | Column::Bucket)));
  if !with_hidden {
    sql = sql.filter(Column::Hidden.eq(false));
  }
  let paginator = sql
    .order_by_asc(Column::Id)
    .into_model()
    .paginate(db, page_size);
  let total = paginator.num_items().await?;
  let challenges = paginator.fetch_page(page - 1).await?;
  Ok((challenges, total))
}

pub async fn get_list<C>(db: &C, game_id: i64, with_hidden: bool) -> Result<Vec<Model>, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .filter(Column::GameId.eq(game_id))
    .select_only()
    .columns(Column::iter().filter(|c| !matches!(c, Column::Content | Column::Bucket)));
  if !with_hidden {
    sql = sql.filter(Column::Hidden.eq(false));
  }
  sql.all(db).await
}

pub async fn get_full_list<C>(db: &C, game_id: i64) -> Result<Vec<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find()
    .filter(Column::GameId.eq(game_id))
    .order_by_asc(Column::Id)
    .all(db)
    .await
}

pub async fn get_by_bucket<C>(db: &C, game_id: i64, bucket: &str) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find()
    .filter(Column::GameId.eq(game_id))
    .filter(Column::Bucket.eq(bucket))
    .one(db)
    .await
}

pub async fn count<C>(
  db: &C, game_id: Option<i64>, game_type: Option<game::HostType>, with_hidden: bool,
) -> Result<u64, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find();
  if let Some(game_id) = game_id {
    sql = sql.filter(Column::GameId.eq(game_id));
  }
  if let Some(game_type) = game_type {
    sql = sql
      .join(JoinType::InnerJoin, Relation::Game.def())
      .filter(game::Column::HostType.eq(game_type));
  }
  if !with_hidden {
    sql = sql.filter(Column::Hidden.eq(false));
  }
  sql.count(db).await
}

pub async fn create<C>(db: &C, challenge: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let challenge = ActiveModel {
    id: ActiveValue::NotSet,
    updated_at: ActiveValue::Set(Utc::now()),
    score: ActiveValue::Set(challenge.score_rule.initial),
    ..challenge.into_active_model().reset_all()
  };
  challenge.insert(db).await
}

pub async fn update<C>(db: &C, challenge: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let challenge = ActiveModel {
    id: ActiveValue::Unchanged(challenge.id),
    updated_at: ActiveValue::Set(Utc::now()),
    score: ActiveValue::NotSet,
    bucket: ActiveValue::NotSet,
    game_id: ActiveValue::NotSet,
    ref_id: ActiveValue::NotSet,
    ..challenge.into_active_model().reset_all()
  };
  challenge.update(db).await
}

pub async fn update_score<C>(db: &C, challenge: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let challenge = ActiveModel {
    id: ActiveValue::Unchanged(challenge.id),
    score: ActiveValue::Set(challenge.score),
    ..challenge.into_active_model()
  };
  challenge.update(db).await
}

pub async fn maintain_score<C>(db: &C, challenge: Model) -> Result<(bool, u64, Model), DbErr>
where
  C: ConnectionTrait, {
  let decay = submission::count(
    db,
    true,
    Some(challenge.game_id),
    Some(challenge.id),
    None,
    None,
    None,
    false,
  )
  .await?;
  let score_rule = &challenge.score_rule;
  let score = if decay < 1 {
    score_rule.initial
  } else if decay >= score_rule.decay as u64 {
    score_rule.minimum
  } else {
    let relative_ratio = (decay as f64 - 1.0) / (score_rule.decay as f64 - 1.0);
    let cos_theta = (relative_ratio * std::f64::consts::PI).cos();
    let normalized_score = (cos_theta + 1.0) / 2.0;
    let score_f = score_rule.minimum as f64
      + (score_rule.initial - score_rule.minimum) as f64 * normalized_score;
    score_f.round() as i32
  };
  let challenge_score_changed = challenge.score != score;
  if challenge_score_changed {
    let challenge = update_score(
      db,
      Model {
        id: challenge.id,
        score,
        ..challenge.clone()
      },
    )
    .await?;
    return Ok((challenge_score_changed, decay, challenge));
  }
  Ok((challenge_score_changed, decay, challenge))
}

pub async fn delete<C>(db: &C, id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_by_id(id).exec(db).await.map(|_| ())
}

/// Returns the prerequisite challenge ids that are not solved yet by the given
/// team, or by the given user when the challenge belongs to a training game
/// without teams.
pub async fn unsatisfied_prerequisites<C>(
  db: &C, challenge: &Model, team_id: Option<i64>, user_id: i64,
) -> Result<Vec<i64>, DbErr>
where
  C: ConnectionTrait, {
  if challenge.prerequisites.0.is_empty() {
    return Ok(vec![]);
  }
  let solves = super::submission::get_list(
    db,
    true,
    false,
    Some(challenge.game_id),
    None,
    team_id,
    (team_id.is_none()).then_some(user_id),
    team_id.is_none(),
  )
  .await?;
  let solved: HashSet<i64> = solves.iter().map(|s| s.challenge_id).collect();
  Ok(
    challenge
      .prerequisites
      .0
      .iter()
      .copied()
      .filter(|id| !solved.contains(id))
      .collect(),
  )
}
