//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{
  DateTime, Utc,
  serde::{ts_seconds, ts_seconds_option},
};
use sea_orm::{
  ActiveValue, FromJsonQueryResult, IntoActiveModel, Iterable, JoinType, QueryOrder, QuerySelect,
  entity::prelude::*,
};
use serde::{Deserialize, Serialize};

use super::submission;
use crate::game;

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct ScoreRule {
  pub initial: i32,
  pub minimum: i32,
  pub decay: i32,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Tag {
  name: String,
  primary: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TagList(pub Vec<Tag>);

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "challenge")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub name: String,
  #[serde(with = "ts_seconds")]
  pub updated_at: DateTime<Utc>,
  #[sea_orm(column_type = "Text")]
  pub content: Option<String>,
  pub hidden: bool,
  pub game_id: i64,
  #[sea_orm(column_type = "JsonBinary")]
  pub tag: TagList,
  #[sea_orm(column_type = "JsonBinary")]
  pub score_rule: ScoreRule,
  pub score: i32,
  pub bucket: Option<String>,
  pub ref_id: Option<i64>,
  #[serde(with = "ts_seconds_option", default = "Option::default")]
  pub release_at: Option<DateTime<Utc>>,
  #[serde(with = "ts_seconds_option", default = "Option::default")]
  pub archive_at: Option<DateTime<Utc>>,
}

impl Model {
  pub fn desensitize(self) -> Self {
    Self {
      bucket: None,
      ..self
    }
  }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::audit::Entity")]
  Audit,
  #[sea_orm(has_many = "super::extra::Entity")]
  Extra,
  #[sea_orm(
    belongs_to = "super::game::Entity",
    from = "Column::GameId",
    to = "super::game::Column::Id",
    on_update = "Cascade",
    on_delete = "Restrict"
  )]
  Game,
  #[sea_orm(has_many = "super::hint::Entity")]
  Hint,
  #[sea_orm(has_many = "super::submission::Entity")]
  Submission,
  #[sea_orm(belongs_to = "Entity", from = "Column::RefId", to = "Column::Id")]
  Original,
}

impl Related<super::audit::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Audit.def()
  }
}

impl Related<super::extra::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Extra.def()
  }
}

impl Related<super::game::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Game.def()
  }
}

impl Related<super::hint::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Hint.def()
  }
}

impl Related<super::submission::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Submission.def()
  }
}

pub struct OriginalLink;

impl Linked for OriginalLink {
  type FromEntity = Entity;

  type ToEntity = Entity;

  fn link(&self) -> Vec<RelationDef> {
    vec![Relation::Original.def()]
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C, id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(id).one(db).await
}

pub async fn get_page<C>(
  db: &C, page: u64, page_size: u64, game_id: i64, with_hidden: bool,
) -> Result<(Vec<Model>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let mut sql = Entity::find()
    .filter(Column::GameId.eq(game_id))
    .select_only()
    .columns(Column::iter().filter(|c| !matches!(c, Column::Content | Column::Bucket)));
  if !with_hidden {
    sql = sql.filter(Column::Hidden.eq(false));
  }
  let paginator = sql
    .order_by_asc(Column::Id)
    .into_model()
    .paginate(db, page_size);
  let total = paginator.num_items().await?;
  let challenges = paginator.fetch_page(page - 1).await?;
  Ok((challenges, total))
}

pub async fn get_list<C>(db: &C, game_id: i64, with_hidden: bool) -> Result<Vec<Model>, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .filter(Column::GameId.eq(game_id))
    .select_only()
    .columns(Column::iter().filter(|c| !matches!(c, Column::Content | Column::Bucket)));
  if !with_hidden {
    sql = sql.filter(Column::Hidden.eq(false));
  }
  sql.all(db).await
}

pub async fn count<C>(
  db: &C, game_id: Option<i64>, game_type: Option<game::HostType>, with_hidden: bool,
) -> Result<u64, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find();
  if let Some(game_id) = game_id {
    sql = sql.filter(Column::GameId.eq(game_id));
  }
  if let Some(game_type) = game_type {
    sql = sql
      .join(JoinType::InnerJoin, Relation::Game.def())
      .filter(game::Column::HostType.eq(game_type));
  }
  if !with_hidden {
    sql = sql.filter(Column::Hidden.eq(false));
  }
  sql.count(db).await
}

pub async fn create<C>(db: &C, challenge: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let challenge = ActiveModel {
    id: ActiveValue::NotSet,
    updated_at: ActiveValue::Set(Utc::now()),
    score: ActiveValue::Set(challenge.score_rule.initial),
    ..challenge.into_active_model().reset_all()
  };
  challenge.insert(db).await
}

pub async fn update<C>(db: &C, challenge: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let challenge = ActiveModel {
    id: ActiveValue::Unchanged(challenge.id),
    updated_at: ActiveValue::Set(Utc::now()),
    score: ActiveValue::NotSet,
    bucket: ActiveValue::NotSet,
    game_id: ActiveValue::NotSet,
    ref_id: ActiveValue::NotSet,
    ..challenge.into_active_model().reset_all()
  };
  challenge.update(db).await
}

pub async fn update_score<C>(db: &C, challenge: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let challenge = ActiveModel {
    id: ActiveValue::Unchanged(challenge.id),
    score: ActiveValue::Set(challenge.score),
    ..challenge.into_active_model()
  };
  challenge.update(db).await
}

pub async fn maintain_score<C>(db: &C, challenge: Model) -> Result<(bool, u64, Model), DbErr>
where
  C: ConnectionTrait, {
  let decay = submission::count(
    db,
    true,
    Some(challenge.game_id),
    Some(challenge.id),
    None,
    None,
    None,
    false,
  )
  .await?;
  let score_rule = &challenge.score_rule;
  let score = if decay < 1 {
    score_rule.initial
  } else if decay >= score_rule.decay as u64 {
    score_rule.minimum
  } else {
    let relative_ratio = (decay as f64 - 1.0) / (score_rule.decay as f64 - 1.0);
    let cos_theta = (relative_ratio * std::f64::consts::PI).cos();
    let normalized_score = (cos_theta + 1.0) / 2.0;
    let score_f = score_rule.minimum as f64
      + (score_rule.initial - score_rule.minimum) as f64 * normalized_score;
    score_f.round() as i32
  };
  let challenge_score_changed = challenge.score != score;
  if challenge_score_changed {
    let challenge = update_score(
      db,
      Model {
        id: challenge.id,
        score,
        ..challenge.clone()
      },
    )
    .await?;
    return Ok((challenge_score_changed, decay, challenge));
  }
  Ok((challenge_score_changed, decay, challenge))
}

pub async fn delete<C>(db: &C, id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
