//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{serde::ts_seconds, DateTime, Utc};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromJsonQueryResult, IntoActiveModel, Iterable, QueryOrder,
    QuerySelect,
};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct ScoreRule {
    pub initial: i32,
    pub minimum: i32,
    pub decay: i32,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Tag {
    name: String,
    primary: bool,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TagList(pub Vec<Tag>);

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "challenge")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    #[serde(with = "ts_seconds")]
    pub updated_at: DateTime<Utc>,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
    pub hidden: bool,
    pub game_id: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub tag: TagList,
    #[sea_orm(column_type = "JsonBinary")]
    pub score_rule: ScoreRule,
    pub score: i32,
    pub bucket: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit::Entity")]
    Audit,
    #[sea_orm(has_many = "super::extra::Entity")]
    Extra,
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Game,
    #[sea_orm(has_many = "super::hint::Entity")]
    Hint,
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
}

impl Related<super::audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Audit.def()
    }
}

impl Related<super::extra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extra.def()
    }
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::hint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hint.def()
    }
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(db: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(id).one(db).await
}

pub async fn get_page(
    db: &DatabaseConnection, page: u64, page_size: u64, game_id: i64, with_hidden: bool,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .select_only()
        .columns(Column::iter().filter(|c| !matches!(c, Column::Content | Column::Bucket)));
    if !with_hidden {
        sql = sql.filter(Column::Hidden.eq(false));
    }
    let paginator = sql
        .order_by_asc(Column::Id)
        .into_model()
        .paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let challenges = paginator.fetch_page(page - 1).await?;
    Ok((challenges, total))
}

pub async fn create(db: &DatabaseConnection, challenge: Model) -> Result<Model, DbErr> {
    let challenge = ActiveModel {
        id: ActiveValue::NotSet,
        updated_at: ActiveValue::Set(Utc::now()),
        score: ActiveValue::Set(challenge.score_rule.initial.clone()),
        ..challenge.into_active_model().reset_all()
    };
    challenge.insert(db).await
}

pub async fn update(db: &DatabaseConnection, challenge: Model) -> Result<Model, DbErr> {
    let challenge = ActiveModel {
        id: ActiveValue::Unchanged(challenge.id),
        updated_at: ActiveValue::Set(Utc::now()),
        score: ActiveValue::NotSet,
        bucket: ActiveValue::NotSet,
        game_id: ActiveValue::NotSet,
        ..challenge.into_active_model().reset_all()
    };
    challenge.update(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
