//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{serde::ts_seconds, DateTime, Utc};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromQueryResult, IntoActiveModel, JoinType, QueryOrder,
    QuerySelect,
};
use serde::{Deserialize, Serialize};

use super::{article, comment_closure, user};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "comment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(with = "ts_seconds")]
    pub created_at: DateTime<Utc>,
    pub article_id: i64,
    pub publisher_id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
    pub id: i64,
    #[serde(with = "ts_seconds")]
    pub created_at: DateTime<Utc>,
    pub article_id: i64,
    pub article_title: String,
    pub publisher_id: i64,
    pub publisher_name: String,
    pub content: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::article::Entity",
        from = "Column::ArticleId",
        to = "super::article::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Article,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::PublisherId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Publisher,
    #[sea_orm(has_many = "super::comment_closure::Entity")]
    Closure,
}

impl Related<super::article::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Article.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Publisher.def()
    }
}

impl Related<super::comment_closure::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Closure.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_list(
    db: &DatabaseConnection, page: u64, page_size: u64, article_id: i64,
) -> Result<(Vec<Model>, u64), DbErr> {
    let sql = Entity::find().filter(Column::ArticleId.eq(article_id));
    let paginator = sql.into_model().paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let comments = paginator.fetch_page(page - 1).await?;
    Ok((comments, total))
}

pub async fn get_list_ex(
    db: &DatabaseConnection, page: u64, page_size: u64, article_id: i64,
) -> Result<(Vec<ExModel>, u64), DbErr> {
    let sql = Entity::find()
        .join(JoinType::InnerJoin, Relation::Publisher.def())
        .join(JoinType::InnerJoin, Relation::Article.def())
        .column_as(user::Column::Nickname, "publisher_name")
        .column_as(article::Column::Title, "article_title")
        .filter(Column::ArticleId.eq(article_id));
    let paginator = sql.into_model().paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let comments = paginator.fetch_page(page - 1).await?;
    Ok((comments, total))
}

pub async fn get_tree(db: &DatabaseConnection, parent_id: i64) -> Result<Vec<Model>, DbErr> {
    let mut sql = Entity::find();
    sql = sql
        .join(JoinType::InnerJoin, Relation::Closure.def())
        .filter(comment_closure::Column::Ancestor.eq(parent_id));
    let articles = sql
        .order_by_desc(Column::CreatedAt)
        .into_model()
        .all(db)
        .await?;
    Ok(articles)
}

pub async fn get_tree_ex(db: &DatabaseConnection, parent_id: i64) -> Result<Vec<ExModel>, DbErr> {
    let mut sql = Entity::find()
        .join(JoinType::InnerJoin, Relation::Publisher.def())
        .join(JoinType::InnerJoin, Relation::Article.def())
        .column_as(user::Column::Nickname, "publisher_name")
        .column_as(article::Column::Title, "article_title");
    sql = sql
        .join(JoinType::InnerJoin, Relation::Closure.def())
        .filter(comment_closure::Column::Ancestor.eq(parent_id));
    let articles = sql
        .order_by_desc(Column::CreatedAt)
        .into_model()
        .all(db)
        .await?;
    Ok(articles)
}

pub async fn create(db: &DatabaseConnection, comment: Model) -> Result<Model, DbErr> {
    let comment = ActiveModel {
        id: ActiveValue::NotSet,
        created_at: ActiveValue::Set(Utc::now()),
        ..comment.into_active_model().reset_all()
    };
    comment.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
