//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "comment_closure")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub ancestor: i64,
    pub descendant: i64,
    pub depth: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::comment::Entity",
        from = "Column::Descendant",
        to = "super::comment::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Descendant,
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Descendant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
