//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use r2s_config::{
    auditor, auth, automate, bucket, cache, captcha, cluster, database, email, logging, media,
    queue, server,
};
use sea_orm::{entity::prelude::*, ActiveValue};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub auditor: Option<auditor::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub auth: Option<auth::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub automate: Option<automate::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub bucket: Option<bucket::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub cache: Option<cache::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub captcha: Option<captcha::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub cluster: Option<cluster::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub database: Option<database::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub email: Option<email::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub logging: Option<logging::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub media: Option<media::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub queue: Option<queue::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub server: Option<server::Config>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(db: &DatabaseConnection) -> Result<Model, DbErr> {
    let config = Entity::find().one(db).await?;
    match config {
        Some(config) => Ok(config),
        None => Err(DbErr::RecordNotFound("config".to_string())),
    }
}

pub async fn update(db: &DatabaseConnection, config: Model) -> Result<Model, DbErr> {
    let original_info = Entity::find().one(db).await?;
    match original_info {
        Some(original_info) => {
            let mut config: ActiveModel = config.into();
            config = config.reset_all();
            config.id = ActiveValue::Unchanged(original_info.id);
            config.update(db).await
        }
        None => {
            let config: ActiveModel = config.into();
            config.insert(db).await
        }
    }
}
