//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use r2s_config::{
  GlobalConfig, auditor, auth, bucket, cache, captcha, cluster, database, email, logging, media,
  queue, server, traits::Merge,
};
use sea_orm::{ActiveValue, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "config")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[sea_orm(column_type = "JsonBinary")]
  pub auditor: Option<auditor::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub auth: Option<auth::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub bucket: Option<bucket::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub cache: Option<cache::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub captcha: Option<captcha::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub cluster: Option<cluster::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub database: Option<database::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub email: Option<email::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub logging: Option<logging::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub media: Option<media::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub queue: Option<queue::Config>,
  #[sea_orm(column_type = "JsonBinary")]
  pub server: Option<server::Config>,
}

impl Model {
  pub fn merge(self, other: GlobalConfig) -> Self {
    // prefers self fields
    Model {
      id: self.id,
      auditor: other.auditor.merge(self.auditor),
      auth: other.auth.merge(self.auth),
      bucket: other.bucket.merge(self.bucket),
      cache: other.cache.merge(self.cache),
      captcha: other.captcha.merge(self.captcha),
      cluster: other.cluster.merge(self.cluster),
      database: other.database.merge(self.database),
      email: other.email.merge(self.email),
      logging: other.logging.merge(self.logging),
      media: other.media.merge(self.media),
      queue: other.queue.merge(self.queue),
      server: other.server.merge(self.server),
    }
  }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find().one(db).await
}

pub async fn update<C>(db: &C, config: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let original_info = Entity::find().one(db).await?;
  match original_info {
    Some(original_info) => {
      let mut config: ActiveModel = config.into();
      config = config.reset_all();
      config.id = ActiveValue::Unchanged(original_info.id);
      config.update(db).await
    }
    None => {
      let config: ActiveModel = config.into();
      config.insert(db).await
    }
  }
}

#[cfg(test)]
mod tests {
  use r2s_config::{GlobalConfig, captcha, database as database_config};

  use super::Model;

  fn dynamic_config() -> Model {
    Model {
      id: 7,
      auditor: None,
      auth: None,
      bucket: None,
      cache: None,
      captcha: Some(captcha::Config {
        enabled: true,
        difficulty: None,
        validator: captcha::ValidatorType::Pow,
      }),
      cluster: None,
      database: Some(database_config::Config {
        db: "dynamic-db".to_owned(),
        host: "db.internal".to_owned(),
        port: 5432,
        user: "postgres".to_owned(),
        password: "secret".to_owned(),
        ssl_mode: "prefer".to_owned(),
      }),
      email: None,
      logging: None,
      media: None,
      queue: None,
      server: None,
    }
  }

  fn global_config() -> GlobalConfig {
    GlobalConfig {
      auditor: None,
      auth: None,
      bucket: None,
      cache: None,
      captcha: Some(captcha::Config {
        enabled: false,
        difficulty: Some(3),
        validator: captcha::ValidatorType::Image,
      }),
      cluster: None,
      database: Some(database_config::Config {
        db: "static-db".to_owned(),
        host: "localhost".to_owned(),
        port: 5432,
        user: "postgres".to_owned(),
        password: "secret".to_owned(),
        ssl_mode: "prefer".to_owned(),
      }),
      email: None,
      logging: None,
      media: None,
      queue: None,
      server: None,
    }
  }

  #[test]
  fn merge_keeps_dynamic_row_id_and_merges_field_wise() {
    let merged = dynamic_config().merge(global_config());

    assert_eq!(merged.id, 7);
    // captcha merges per field: database switch/validator win, static
    // difficulty fills the gap left by the database row.
    let captcha = merged.captcha.unwrap();
    assert!(captcha.enabled);
    assert_eq!(captcha.validator, captcha::ValidatorType::Pow);
    assert_eq!(captcha.difficulty, Some(3));
    // database prefers the dynamic (database side) config.
    assert_eq!(merged.database.unwrap().db, "dynamic-db");
    assert!(merged.auth.is_none());
  }
}
