//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use r2s_config::{
    auditor, auth, automate, bucket, cache, captcha, cluster, database, email, logging, media,
    queue, server, traits::Merge, GlobalConfig,
};
use sea_orm::{entity::prelude::*, ActiveValue};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub auditor: Option<auditor::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub auth: Option<auth::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub automate: Option<automate::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub bucket: Option<bucket::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub cache: Option<cache::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub captcha: Option<captcha::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub cluster: Option<cluster::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub database: Option<database::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub email: Option<email::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub logging: Option<logging::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub media: Option<media::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub queue: Option<queue::Config>,
    #[sea_orm(column_type = "JsonBinary")]
    pub server: Option<server::Config>,
}

impl Model {
    pub fn merge(self, other: GlobalConfig) -> Self {
        // prefers self fields
        Model {
            id: self.id,
            auditor: other.auditor.merge(self.auditor),
            auth: other.auth.merge(self.auth),
            automate: other.automate.merge(self.automate),
            bucket: other.bucket.merge(self.bucket),
            cache: other.cache.merge(self.cache),
            captcha: other.captcha.merge(self.captcha),
            cluster: other.cluster.merge(self.cluster),
            database: other.database.merge(self.database),
            email: other.email.merge(self.email),
            logging: other.logging.merge(self.logging),
            media: other.media.merge(self.media),
            queue: other.queue.merge(self.queue),
            server: other.server.merge(self.server),
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(db: &DatabaseConnection) -> Result<Option<Model>, DbErr> {
    Entity::find().one(db).await
}

pub async fn update(db: &DatabaseConnection, config: Model) -> Result<Model, DbErr> {
    let original_info = Entity::find().one(db).await?;
    match original_info {
        Some(original_info) => {
            let mut config: ActiveModel = config.into();
            config = config.reset_all();
            config.id = ActiveValue::Unchanged(original_info.id);
            config.update(db).await
        }
        None => {
            let config: ActiveModel = config.into();
            config.insert(db).await
        }
    }
}
