//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{DateTime, Utc, serde::ts_seconds};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{
  ActiveValue, FromJsonQueryResult, FromQueryResult, IntoActiveModel, IntoSimpleExpr, Order,
  QueryOrder, QuerySelect, entity::prelude::*,
};
use sea_query::{BinOper, Query, SimpleExpr};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use crate::team;

#[derive(
  Clone,
  Debug,
  Default,
  PartialEq,
  Eq,
  PartialOrd,
  Serialize_repr,
  Deserialize_repr,
  EnumIter,
  DeriveActiveEnum,
  FromPrimitive,
  ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum HostType {
  #[default]
  Training = 0,
  Game     = 1,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct AccessPolicy {
  pub restrict: bool,
  /// institutes that are allowed to register and be ranked.
  pub institutes: Vec<i64>,
  /// for platform sync.
  ///
  /// 0. sync without restrictions
  /// 1. sync with game admin access
  /// 2. no sync
  ///
  /// note that sync will only be allowed when the game is archived.
  pub sync: i32,
}

// NOTE: Policy Structs
// Each struct must have a default implementation for all their fields.
// And please add `#[serde(default)]` to each field.
// It's because that the policy may update its fields in the future, and it's
// hard to update all this column in the database for all outdated games.

fn default_true() -> bool {
  true
}
/// Archive policy -> Challenge
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct ArchivePolicyChallenge {
  #[serde(default)]
  pub show_answer: bool,
  #[serde(default)]
  pub show_hints: bool,
}

/// Archive policy
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct ArchivePolicy {
  #[serde(default)]
  pub challenge: ArchivePolicyChallenge,
}

/// Hammer policy
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct HammerPolicy {
  #[serde(default = "default_true")]
  pub enabled: bool,
  #[serde(default)]
  pub outer_label: Option<String>,
  #[serde(default)]
  pub outer_url: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Admins(pub Vec<i64>);

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct AwardRates(pub Vec<i32>);

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TimelinePreset {
  pub label: String,
  #[serde(with = "ts_seconds")]
  pub start_at: DateTime<Utc>,
  #[serde(with = "ts_seconds")]
  pub end_at: DateTime<Utc>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TimelinePresets(pub Vec<TimelinePreset>);
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "game")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[serde(with = "ts_seconds")]
  pub updated_at: DateTime<Utc>,
  pub name: String,
  pub brief: String,
  pub introduction_id: Option<i64>,
  #[serde(with = "ts_seconds")]
  pub start_at: DateTime<Utc>,
  #[serde(with = "ts_seconds")]
  pub end_at: DateTime<Utc>,
  #[serde(with = "ts_seconds")]
  pub register_at: DateTime<Utc>,
  #[serde(with = "ts_seconds")]
  pub archive_at: DateTime<Utc>,
  pub hidden: bool,
  pub offline: bool,
  pub frozen: bool,
  pub host_type: HostType,
  pub team_size: i32,
  #[sea_orm(column_type = "JsonBinary")]
  pub access_policy: AccessPolicy,
  #[sea_orm(column_type = "JsonBinary")]
  #[serde(default = "ArchivePolicy::default")]
  pub archive_policy: ArchivePolicy,
  #[sea_orm(column_type = "JsonBinary")]
  #[serde(default = "HammerPolicy::default")]
  pub hammer_policy: HammerPolicy,
  pub cover: Option<String>,
  pub logo: Option<String>,
  pub enable_audit: bool,
  pub can_register_after_started: bool,
  pub award_rate: i32,
  #[sea_orm(column_type = "JsonBinary")]
  pub award_rates: Option<AwardRates>,
  #[sea_orm(column_type = "JsonBinary")]
  pub admins: Admins,
  pub weight: i32,
  pub bucket: Option<String>,
  pub token: Option<String>,
  #[sea_orm(column_type = "JsonBinary")]
  pub timeline_presets: Option<TimelinePresets>,
  #[serde(default = "Option::default")]
  pub node_selector: Option<String>,
  #[serde(default = "Option::default")]
  pub traffic: Option<String>,
  #[serde(default = "Option::default")]
  pub lifecycle: Option<String>,
}

impl Model {
  pub fn desensitize(self) -> Self {
    Self {
      bucket: None,
      token: None,
      node_selector: None,
      traffic: None,
      lifecycle: None,
      ..self
    }
  }

  pub fn in_progress(&self) -> bool {
    self.host_type == HostType::Game && self.start_at <= Utc::now() && self.end_at >= Utc::now()
  }

  pub fn archived(&self) -> bool {
    self.host_type == HostType::Game && self.archive_at <= Utc::now()
  }
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct StatisticsModel {
  pub id: i64,
  pub name: String,
  #[serde(with = "ts_seconds")]
  pub start_at: DateTime<Utc>,
  #[serde(with = "ts_seconds")]
  pub end_at: DateTime<Utc>,
  #[serde(with = "ts_seconds")]
  pub register_at: DateTime<Utc>,
  #[serde(with = "ts_seconds")]
  pub archive_at: DateTime<Utc>,
  // NOTE: should be u64, but sqlx does not support u64
  pub teams: i64,
  pub host_type: HostType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::article::Entity",
    from = "Column::IntroductionId",
    to = "super::article::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Introduction,
  #[sea_orm(has_many = "super::challenge::Entity")]
  Challenge,
  #[sea_orm(has_many = "super::notification::Entity")]
  Notification,
  #[sea_orm(has_many = "super::team::Entity")]
  Team,
}

impl Related<super::article::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Introduction.def()
  }
}

impl Related<super::challenge::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Challenge.def()
  }
}

impl Related<super::notification::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Notification.def()
  }
}

impl Related<super::team::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Team.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C, game_id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(game_id).one(db).await
}

pub async fn get_by_bucket<C>(db: &C, bucket: &str) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find()
    .filter(Column::Bucket.eq(bucket))
    .one(db)
    .await
}

pub async fn get_page<C>(
  db: &C, page: u64, page_size: u64, host_type: Option<HostType>, weight: Option<i32>,
  with_hidden: bool,
) -> Result<(Vec<Model>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let mut sql = Entity::find();
  if let Some(host_type) = host_type {
    sql = sql.filter(Column::HostType.eq(host_type));
  }
  if let Some(weight) = weight {
    sql = sql.filter(Column::Weight.eq(weight));
  }
  if !with_hidden {
    sql = sql.filter(Column::Hidden.eq(false));
  }
  sql = sql.order_by(Column::StartAt, Order::Desc);
  let paginator = sql.into_model().paginate(db, page_size);
  let total = paginator.num_items().await?;
  let games: Vec<Model> = paginator.fetch_page(page - 1).await?;
  Ok((
    games.iter().map(|g| g.clone().desensitize()).collect(),
    total,
  ))
}

pub async fn get_list<C>(
  db: &C, register_at: Option<DateTime<Utc>>, start_at: Option<DateTime<Utc>>,
  end_at: Option<DateTime<Utc>>, archive_at: Option<DateTime<Utc>>,
) -> Result<Vec<Model>, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find().filter(Column::HostType.eq(HostType::Game));
  if let Some(register_at) = register_at {
    sql = sql.filter(Column::RegisterAt.lte(register_at));
  }
  if let Some(start_at) = start_at {
    sql = sql.filter(Column::StartAt.lte(start_at));
  }
  if let Some(end_at) = end_at {
    sql = sql.filter(Column::EndAt.gte(end_at));
  }
  if let Some(archive_at) = archive_at {
    sql = sql.filter(Column::ArchiveAt.gte(archive_at));
  }

  sql.all(db).await
}

pub async fn get_statistics<C>(db: &C) -> Result<Vec<StatisticsModel>, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find().select_only().columns(vec![
    Column::Id,
    Column::Name,
    Column::StartAt,
    Column::EndAt,
    Column::RegisterAt,
    Column::ArchiveAt,
    Column::HostType,
  ]);
  sql = sql.column_as(
    SimpleExpr::SubQuery(
      None,
      Box::new(
        Query::select()
          .expr(team::Column::GameId.count())
          .and_where(SimpleExpr::Binary(
            Box::new(Column::Id.into_simple_expr()),
            BinOper::Equal,
            Box::new(team::Column::GameId.into_simple_expr()),
          ))
          .from(team::Entity)
          .take()
          .into_sub_query_statement(),
      ),
    ),
    "teams",
  );

  sql.into_model::<StatisticsModel>().all(db).await
}

pub async fn create<C>(db: &C, game: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let game = ActiveModel {
    id: ActiveValue::NotSet,
    updated_at: ActiveValue::Set(Utc::now()),
    ..game.into_active_model().reset_all()
  };
  game.insert(db).await
}

pub async fn update<C>(db: &C, game: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let game = ActiveModel {
    id: ActiveValue::Unchanged(game.id),
    updated_at: ActiveValue::Set(Utc::now()),
    ..game.into_active_model().reset_all()
  };
  game.update(db).await
}

pub async fn delete<C>(db: &C, game_id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_by_id(game_id).exec(db).await.map(|_| ())
}

#[cfg(test)]
mod tests {
  use chrono::{Duration, Utc};

  use super::{AccessPolicy, Admins, ArchivePolicy, HammerPolicy, HostType, Model};

  fn sample_game(
    host_type: HostType, start_offset_seconds: i64, end_offset_seconds: i64,
    archive_offset_seconds: i64,
  ) -> Model {
    let now = Utc::now();
    Model {
      id: 1,
      updated_at: now,
      name: "sample".to_owned(),
      brief: "sample brief".to_owned(),
      introduction_id: None,
      start_at: now + Duration::seconds(start_offset_seconds),
      end_at: now + Duration::seconds(end_offset_seconds),
      register_at: now - Duration::days(1),
      archive_at: now + Duration::seconds(archive_offset_seconds),
      hidden: false,
      offline: false,
      frozen: false,
      host_type,
      team_size: 4,
      access_policy: AccessPolicy {
        restrict: false,
        institutes: vec![],
        sync: 0,
      },
      archive_policy: ArchivePolicy::default(),
      hammer_policy: HammerPolicy::default(),
      cover: Some("cover".to_owned()),
      logo: Some("logo".to_owned()),
      enable_audit: true,
      can_register_after_started: false,
      award_rate: 100,
      award_rates: None,
      admins: Admins(vec![1]),
      weight: 10,
      bucket: Some("bucket".to_owned()),
      token: Some("token".to_owned()),
      timeline_presets: None,
      node_selector: Some("node-a".to_owned()),
      traffic: Some("traffic script".to_owned()),
      lifecycle: Some("lifecycle script".to_owned()),
    }
  }

  #[test]
  fn desensitize_clears_sensitive_runtime_fields() {
    let game = sample_game(HostType::Game, -3600, 3600, 7200);

    let desensitized = game.clone().desensitize();

    assert_eq!(desensitized.name, game.name);
    assert_eq!(desensitized.bucket, None);
    assert_eq!(desensitized.token, None);
    assert_eq!(desensitized.node_selector, None);
    assert_eq!(desensitized.traffic, None);
    assert_eq!(desensitized.lifecycle, None);
  }

  #[test]
  fn in_progress_requires_game_host_type_and_active_time_window() {
    assert!(sample_game(HostType::Game, -3600, 3600, 7200).in_progress());
    assert!(!sample_game(HostType::Game, 3600, 7200, 10800).in_progress());
    assert!(!sample_game(HostType::Game, -7200, -3600, 3600).in_progress());
    assert!(!sample_game(HostType::Training, -3600, 3600, 7200).in_progress());
  }

  #[test]
  fn archived_requires_game_host_type_and_elapsed_archive_time() {
    assert!(sample_game(HostType::Game, -7200, -3600, -60).archived());
    assert!(!sample_game(HostType::Game, -3600, 3600, 3600).archived());
    assert!(!sample_game(HostType::Training, -7200, -3600, -60).archived());
  }
}
