//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{
    serde::{ts_seconds, ts_seconds_option},
    DateTime, Utc,
};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{entity::prelude::*, ActiveValue, FromJsonQueryResult, IntoActiveModel};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum HostType {
    #[default]
    CTFTraining = 0,
    CTFGame = 1,
}
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct AccessPolicy {
    pub restrict: bool,
    pub institutes: Vec<i64>,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(with = "ts_seconds")]
    pub updated_at: DateTime<Utc>,
    pub name: String,
    pub brief: String,
    pub introduction_id: i64,
    #[serde(with = "ts_seconds")]
    pub start_at: DateTime<Utc>,
    #[serde(with = "ts_seconds_option")]
    pub end_at: Option<DateTime<Utc>>,
    #[serde(with = "ts_seconds_option")]
    pub register_at: Option<DateTime<Utc>>,
    #[serde(with = "ts_seconds_option")]
    pub archive_at: Option<DateTime<Utc>>,
    pub hidden: bool,
    pub offline: bool,
    pub frozen: bool,
    pub host_type: HostType,
    pub team_size: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub access_policy: AccessPolicy,
    pub cover: Option<String>,
    pub logo: Option<String>,
    pub enable_audit: bool,
    pub can_register_after_started: bool,
    pub award_rate: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::article::Entity",
        from = "Column::IntroductionId",
        to = "super::article::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Introduction,
    #[sea_orm(has_many = "super::challenge::Entity")]
    Challenge,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::team::Entity")]
    Team,
}

impl Related<super::article::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Introduction.def()
    }
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(db: &DatabaseConnection, game_id: i64) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(game_id).one(db).await
}

pub async fn get_page(
    db: &DatabaseConnection, page: u64, page_size: u64, host_type: Option<HostType>,
    with_hidden: bool,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find();
    if let Some(host_type) = host_type {
        sql = sql.filter(Column::HostType.eq(host_type));
    }
    if !with_hidden {
        sql = sql.filter(Column::Hidden.eq(false));
    }
    let paginator = sql.into_model().paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let games = paginator.fetch_page(page - 1).await?;
    Ok((games, total))
}

pub async fn create(db: &DatabaseConnection, game: Model) -> Result<Model, DbErr> {
    let game = ActiveModel {
        id: ActiveValue::NotSet,
        updated_at: ActiveValue::Set(Utc::now()),
        ..game.into_active_model().reset_all()
    };
    game.insert(db).await
}

pub async fn update(db: &DatabaseConnection, game: Model) -> Result<Model, DbErr> {
    let game = ActiveModel {
        id: ActiveValue::Unchanged(game.id),
        updated_at: ActiveValue::Set(Utc::now()),
        ..game.into_active_model().reset_all()
    };
    game.update(db).await
}

pub async fn delete(db: &DatabaseConnection, game_id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(game_id).exec(db).await.map(|_| ())
}
