//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{serde::ts_seconds, DateTime, Utc};
use sea_orm::{
    entity::prelude::*, ActiveValue, Condition, IntoActiveModel, IntoSimpleExpr, RelationTrait,
};
use sea_query::{BinOper, Expr, Query, SimpleExpr};
use serde::{Deserialize, Serialize};

use super::submission;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "hint")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(with = "ts_seconds")]
    pub created_at: DateTime<Utc>,
    pub challenge_id: i64,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    /// Use score to unlock this hint.
    pub cost: i32,
    /// Auto release hint at this time.
    #[serde(with = "ts_seconds")]
    pub release_at: DateTime<Utc>,
    /// Only release this hint when no solves of the challenge at `release_at`
    /// time.
    pub no_solves_only: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
    #[sea_orm(has_many = "super::extra::Entity")]
    Extra,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::extra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extra.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_list(
    db: &DatabaseConnection, challenge_id: i64, with_all: bool,
) -> Result<Vec<Model>, DbErr> {
    let mut sql = Entity::find().filter(Column::ChallengeId.eq(challenge_id));
    if !with_all {
        // SELECT hint.*
        // FROM hint
        // WHERE hint.challenge_id = $1
        //   AND hint.release_at <= now()
        //   AND (no_solves_only = FALSE OR (
        //     NOT EXISTS(SELECT *
        //                FROM submission
        //                WHERE submission.challenge_id = 1
        //                  AND submission.created_at <= hint.release_at
        //                  AND submission.solved = TRUE)))
        sql = sql.filter(Column::ReleaseAt.lte(Utc::now())).filter(
            Condition::any().add(Column::NoSolvesOnly.eq(false)).add(
                Expr::exists(
                    Query::select()
                        .column(submission::Column::Id)
                        .and_where(submission::Column::ChallengeId.eq(challenge_id))
                        .and_where(SimpleExpr::Binary(
                            Box::new(submission::Column::CreatedAt.into_simple_expr()),
                            BinOper::SmallerThanOrEqual,
                            Box::new(Column::ReleaseAt.into_simple_expr()),
                        ))
                        .and_where(submission::Column::Solved.eq(true))
                        .from(submission::Entity)
                        .take(),
                )
                .not(),
            ),
        )
    }
    sql.all(db).await
}

pub async fn create(db: &DatabaseConnection, hint: Model) -> Result<Model, DbErr> {
    let hint = ActiveModel {
        id: ActiveValue::NotSet,
        created_at: ActiveValue::Set(Utc::now()),
        ..hint.into_active_model().reset_all()
    };
    hint.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, hint_id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(hint_id).exec(db).await.map(|_| ())
}

// #[cfg(test)]
// mod tests {
//     use super::get_list;
//     use sea_orm::{ConnectOptions, Database, DatabaseConnection};

//     #[tokio::test]
//     async fn test_get_hints() {
//         let mut connect_options = ConnectOptions::new(
//             // development only
//
// "postgresql://ret2shell:P@ssw02dInD3v3l0pm3nt@localhost:5432/ret2shell",
//         );
//         connect_options.acquire_timeout(std::time::Duration::from_secs(15));

//         let db: DatabaseConnection =
// Database::connect(connect_options).await.unwrap();         println!("{:?}",
// get_list(&db, 1, false).await.unwrap());     }
// }
