//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{
    serde::{ts_seconds, ts_seconds_option},
    DateTime, Utc,
};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromQueryResult, IntoActiveModel, JoinType, QueryOrder,
    QuerySelect,
};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use super::{challenge, team, user};

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum State {
    #[default]
    Pending = 0,
    Running = 1,
    Succeeded = 2,
    Failed = 3,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "instance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub inner_addr: Option<String>,
    #[sea_orm(unique)]
    pub proxy_addr: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Option<Json>,
    pub renew_count: i32,
    #[serde(with = "ts_seconds_option")]
    pub started_at: Option<DateTime<Utc>>,
    #[serde(with = "ts_seconds")]
    pub created_at: DateTime<Utc>,
    #[serde(with = "ts_seconds_option")]
    pub stoped_at: Option<DateTime<Utc>>,
    pub user_id: Option<i64>,
    pub team_id: Option<i64>,
    pub challenge_id: i64,
    pub state: State,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Option<Json>,
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
    pub id: i64,
    pub name: String,
    pub inner_addr: Option<String>,
    pub proxy_addr: String,
    pub data: Option<Json>,
    pub renew_count: i32,
    #[serde(with = "ts_seconds")]
    pub started_at: DateTime<Utc>,
    pub user_id: i64,
    pub user_name: String,
    pub team_id: Option<i64>,
    pub team_name: Option<String>,
    pub challenge_id: i64,
    pub challenge_name: String,
    pub state: State,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Challenge,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Team,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_page(
    db: &DatabaseConnection, page: u64, page_size: u64, challenge_id: Option<i64>,
    user_id: Option<i64>, team_id: Option<i64>,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find();
    if let Some(challenge_id) = challenge_id {
        sql = sql.filter(Column::ChallengeId.eq(challenge_id));
    }
    if let Some(user_id) = user_id {
        sql = sql.filter(Column::UserId.eq(user_id));
    }
    if let Some(team_id) = team_id {
        sql = sql.filter(Column::TeamId.eq(team_id));
    }
    sql = sql
        .order_by_asc(Column::State)
        .order_by_desc(Column::StartedAt);
    let paginator = sql.into_model().paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let instances = paginator.fetch_page(page - 1).await?;
    Ok((instances, total))
}

pub async fn get_page_ex(
    db: &DatabaseConnection, page: u64, page_size: u64, challenge_id: Option<i64>,
    user_id: Option<i64>, team_id: Option<i64>,
) -> Result<(Vec<ExModel>, u64), DbErr> {
    let mut sql = Entity::find()
        .join(JoinType::InnerJoin, Relation::Team.def())
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .join(JoinType::InnerJoin, Relation::User.def())
        .column_as(user::Column::Nickname, "user_name")
        .column_as(team::Column::Name, "team_name")
        .column_as(challenge::Column::Name, "challenge_name");
    if let Some(challenge_id) = challenge_id {
        sql = sql.filter(Column::ChallengeId.eq(challenge_id));
    }
    if let Some(user_id) = user_id {
        sql = sql.filter(Column::UserId.eq(user_id));
    }
    if let Some(team_id) = team_id {
        sql = sql.filter(Column::TeamId.eq(team_id));
    }
    sql = sql
        .order_by_asc(Column::State)
        .order_by_desc(Column::StartedAt);
    let paginator = sql.into_model().paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let instances = paginator.fetch_page(page - 1).await?;
    Ok((instances, total))
}

pub async fn get_by_user_id(
    db: &DatabaseConnection, user_id: i64, with_all: bool,
) -> Result<Option<Model>, DbErr> {
    let mut sql = Entity::find().filter(Column::UserId.eq(user_id));
    if !with_all {
        sql = sql.filter(Column::State.lte(State::Running));
    }
    sql.one(db).await
}

pub async fn get_by_user_id_ex(
    db: &DatabaseConnection, user_id: i64, with_all: bool,
) -> Result<Option<ExModel>, DbErr> {
    let mut sql = Entity::find()
        .join(JoinType::InnerJoin, Relation::Team.def())
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .join(JoinType::InnerJoin, Relation::User.def())
        .column_as(user::Column::Nickname, "user_name")
        .column_as(team::Column::Name, "team_name")
        .column_as(challenge::Column::Name, "challenge_name")
        .filter(Column::UserId.eq(user_id));
    if !with_all {
        sql = sql.filter(Column::State.lte(State::Running));
    }
    sql.into_model().one(db).await
}

pub async fn get_list_by_team_id(
    db: &DatabaseConnection, team_id: i64, with_all: bool,
) -> Result<Vec<Model>, DbErr> {
    let mut sql = Entity::find().filter(Column::TeamId.eq(team_id));
    if !with_all {
        sql = sql.filter(Column::State.lte(State::Running));
    }
    sql.all(db).await
}

pub async fn get_list_by_team_id_ex(
    db: &DatabaseConnection, team_id: i64, with_all: bool,
) -> Result<Vec<ExModel>, DbErr> {
    let mut sql = Entity::find()
        .join(JoinType::InnerJoin, Relation::Team.def())
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .join(JoinType::InnerJoin, Relation::User.def())
        .column_as(user::Column::Nickname, "user_name")
        .column_as(team::Column::Name, "team_name")
        .column_as(challenge::Column::Name, "challenge_name")
        .filter(Column::TeamId.eq(team_id));
    if !with_all {
        sql = sql.filter(Column::State.lte(State::Running));
    }
    sql.into_model().all(db).await
}

pub async fn create(db: &DatabaseConnection, instance: Model) -> Result<Model, DbErr> {
    let instance = ActiveModel {
        id: ActiveValue::NotSet,
        ..instance.into_active_model().reset_all()
    };
    instance.insert(db).await
}

pub async fn update(db: &DatabaseConnection, instance: Model) -> Result<Model, DbErr> {
    let instance = ActiveModel {
        id: ActiveValue::Unchanged(instance.id),
        ..instance.into_active_model().reset_all()
    };
    instance.update(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
