//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

use super::user;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ip")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user2_ip::Entity")]
    User2Ip,
}

impl Related<super::user2_ip::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Ip.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_ip::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_ip::Relation::Ip.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_ip_list(db: &DatabaseConnection, user_id: i64) -> Result<Vec<Model>, DbErr> {
    let user = user::Entity::find()
        .filter(Column::Id.eq(user_id))
        .one(db)
        .await?;
    match user {
        Some(user) => Ok(user.find_related(Entity).all(db).await?),
        None => Err(DbErr::RecordNotFound("user".to_string())),
    }
}
