//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::{entity::prelude::*, ActiveValue, IntoActiveModel};
use serde::{Deserialize, Serialize};

use super::{user, user2_ip};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ip")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user2_ip::Entity")]
    User2Ip,
}

impl Related<super::user2_ip::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Ip.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_ip::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_ip::Relation::Ip.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_list(db: &DatabaseConnection, user_id: i64) -> Result<Vec<Model>, DbErr> {
    let user = user::Entity::find()
        .filter(Column::Id.eq(user_id))
        .one(db)
        .await?;
    match user {
        Some(user) => Ok(user.find_related(Entity).all(db).await?),
        None => Err(DbErr::RecordNotFound("user".to_string())),
    }
}

pub async fn get_or_create(db: &DatabaseConnection, address: &str) -> Result<Model, DbErr> {
    match Entity::find()
        .filter(Column::Address.eq(address))
        .one(db)
        .await?
    {
        Some(ip) => Ok(ip),
        None => {
            create(
                db,
                Model {
                    id: 0,
                    address: address.to_string(),
                },
            )
            .await
        }
    }
}

pub async fn create(db: &DatabaseConnection, ip: Model) -> Result<Model, DbErr> {
    let ip = ActiveModel {
        id: ActiveValue::NotSet,
        ..ip.into_active_model().reset_all()
    };
    ip.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}

pub async fn link_user(db: &DatabaseConnection, user_id: i64, ip_id: i64) -> Result<(), DbErr> {
    if user2_ip::Entity::find()
        .filter(user2_ip::Column::UserId.eq(user_id))
        .filter(user2_ip::Column::IpAddressId.eq(ip_id))
        .one(db)
        .await?
        .is_some()
    {
        return Ok(());
    }
    let user2ip = user2_ip::ActiveModel {
        id: ActiveValue::NotSet,
        user_id: ActiveValue::Set(user_id),
        ip_address_id: ActiveValue::Set(ip_id),
    };
    user2ip.insert(db).await.map(|_| ())
}
