//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::{entity::prelude::*, ActiveValue, IntoActiveModel};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "media")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub path: String,
    #[sea_orm(unique)]
    pub hash: String,
    pub uploader_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UploaderId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(db: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(id).one(db).await
}

pub async fn get_by_hash(db: &DatabaseConnection, hash: &str) -> Result<Option<Model>, DbErr> {
    Entity::find().filter(Column::Hash.eq(hash)).one(db).await
}

pub async fn get_list(db: &DatabaseConnection, uploader_id: i64) -> Result<Vec<Model>, DbErr> {
    Entity::find()
        .filter(Column::UploaderId.eq(uploader_id))
        .all(db)
        .await
}

pub async fn create(db: &DatabaseConnection, media: Model) -> Result<Model, DbErr> {
    let media = ActiveModel {
        id: ActiveValue::NotSet,
        ..media.into_active_model().reset_all()
    };
    media.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}

pub async fn delete_by_user_id(db: &DatabaseConnection, user_id: i64) -> Result<(), DbErr> {
    Entity::delete(ActiveModel {
        uploader_id: ActiveValue::Set(user_id),
        ..Default::default()
    })
    .exec(db)
    .await
    .map(|_| ())
}
