//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod article;
pub mod audit;
pub mod calendar;
pub mod challenge;
pub mod chat;
pub mod comment;
pub mod config;
pub mod extra;
pub mod game;
pub mod game_registry_source;
pub mod game_release;
pub mod game_remote_sync;
pub mod game_sync_job;
pub mod hint;
pub mod institute;
pub mod ip;
pub mod media;
pub mod notification;
pub mod oauth;
pub mod oauth_provider;
pub mod submission;
pub mod team;
pub mod user;
pub mod user2_ip;
pub mod user2_team;
