//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{
    serde::ts_seconds::{deserialize as from_ts, serialize as to_ts},
    DateTime, Utc,
};
use sea_orm::{entity::prelude::*, ActiveValue, IntoActiveModel};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub published_at: DateTime<Utc>,
    pub game_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_list(db: &DatabaseConnection, game_id: i64) -> Result<Vec<Model>, DbErr> {
    let notifications = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .all(db)
        .await?;
    Ok(notifications)
}

pub async fn create(db: &DatabaseConnection, notification: Model) -> Result<Model, DbErr> {
    let notification = ActiveModel {
        id: ActiveValue::NotSet,
        ..notification.into_active_model().reset_all()
    };
    notification.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
