//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{serde::ts_seconds, DateTime, Utc};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromQueryResult, IntoActiveModel, JoinType, QuerySelect,
};
use serde::{Deserialize, Serialize};

use super::user;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "notification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[serde(with = "ts_seconds")]
    pub published_at: DateTime<Utc>,
    pub game_id: i64,
    pub uploader_id: i64,
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
    pub id: i64,
    pub title: String,
    pub content: String,
    #[serde(with = "ts_seconds")]
    pub published_at: DateTime<Utc>,
    pub game_id: i64,
    pub uploader_id: i64,
    pub uploader_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UploaderId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Uploader,
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Uploader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_list(db: &DatabaseConnection, game_id: i64) -> Result<Vec<Model>, DbErr> {
    let notifications = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .all(db)
        .await?;
    Ok(notifications)
}

pub async fn get_list_ex(db: &DatabaseConnection, game_id: i64) -> Result<Vec<ExModel>, DbErr> {
    let notifications = Entity::find()
        .join(JoinType::InnerJoin, Relation::Uploader.def())
        .column_as(user::Column::Nickname, "uploader_name")
        .filter(Column::GameId.eq(game_id))
        .into_model()
        .all(db)
        .await?;
    Ok(notifications)
}

pub async fn create(db: &DatabaseConnection, notification: Model) -> Result<Model, DbErr> {
    let notification = ActiveModel {
        id: ActiveValue::NotSet,
        ..notification.into_active_model().reset_all()
    };
    notification.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
