//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::{ActiveValue, IntoActiveModel, entity::prelude::*};
use serde::{Deserialize, Serialize};
use validator::{Validate, ValidationError};

use crate::validation::{char_len, non_blank, optional_url};

fn provider_slug(value: &str) -> Result<(), ValidationError> {
  let len = char_len(value);
  if !(2..=32).contains(&len)
    || !value
      .chars()
      .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
  {
    return Err(ValidationError::new("provider_slug"));
  }
  Ok(())
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Validate)]
#[sea_orm(table_name = "oauth_provider")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[validate(custom(function = "non_blank", message = "oauth provider name is required"))]
  pub name: String,
  pub avatar: Option<String>,
  #[validate(custom(
    function = "provider_slug",
    message = "oauth provider contains invalid characters"
  ))]
  pub provider: String,
  #[sea_orm(column_type = "Text", nullable)]
  #[validate(custom(function = "non_blank", message = "oauth provider script is required"))]
  pub script: String,
  #[sea_orm(column_type = "Text", nullable)]
  #[validate(custom(
    function = "optional_url",
    message = "oauth provider portal is invalid"
  ))]
  pub portal: Option<String>,
}

impl Model {
  pub fn desensitize(self) -> Self {
    Self {
      script: "".to_owned(),
      ..self
    }
  }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C, id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(id).one(db).await
}

pub async fn get_by_provider<C>(db: &C, provider: &str) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find()
    .filter(Column::Provider.eq(provider))
    .one(db)
    .await
}

pub async fn get_list<C>(db: &C) -> Result<Vec<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find().all(db).await
}

pub async fn create<C>(db: &C, oauth: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let oauth = ActiveModel {
    id: ActiveValue::NotSet,
    ..oauth.into_active_model().reset_all()
  };
  oauth.insert(db).await
}

pub async fn update<C>(db: &C, id: i64, oauth: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let oauth = ActiveModel {
    id: ActiveValue::Unchanged(id),
    ..oauth.into_active_model().reset_all()
  };
  oauth.update(db).await
}

pub async fn delete<C>(db: &C, id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
