//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{entity::prelude::*, ActiveValue, FromJsonQueryResult, IntoActiveModel};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum PermType {
    #[default]
    Game = 0,
    User = 1,
    Statistics = 2,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct PolicyGame {
    pub game_id: i64,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct PolicyUser {
    pub institute_id: Option<i64>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct PolicyStatistics {
    pub institute_id: Option<i64>,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub enum PolicyRule {
    Game(PolicyGame),
    User(PolicyUser),
    Statistics(PolicyStatistics),
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "policy")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub perm_type: PermType,
    #[sea_orm(column_type = "JsonBinary")]
    pub rule: PolicyRule,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(
    db: &DatabaseConnection, user_id: Option<i64>, perm_type: Option<PermType>,
) -> Result<Vec<Model>, DbErr> {
    let mut sql = Entity::find();
    if let Some(user_id) = user_id {
        sql = sql.filter(Column::UserId.eq(user_id));
    }
    if let Some(perm_type) = perm_type {
        sql = sql.filter(Column::PermType.eq(perm_type));
    }
    sql.all(db).await
}

pub async fn create(db: &DatabaseConnection, policy: Model) -> Result<Model, DbErr> {
    let policy = ActiveModel {
        id: ActiveValue::NotSet,
        ..policy.into_active_model().reset_all()
    };
    policy.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
