//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::{
    article::Entity as Article, article_closure::Entity as ArticleClosure, audit::Entity as Audit,
    calendar::Entity as Calendar, challenge::Entity as Challenge, comment::Entity as Comment,
    comment_closure::Entity as CommentClosure, config::Entity as Config, extra::Entity as Extra,
    game::Entity as Game, hint::Entity as Hint, instance::Entity as Instance,
    institute::Entity as Institute, ip::Entity as Ip, media::Entity as Media,
    notification::Entity as Notification, oauth::Entity as Oauth, submission::Entity as Submission,
    team::Entity as Team, user::Entity as User, user2_ip::Entity as User2Ip,
    user2_team::Entity as User2Team,
};
