//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{DateTime, Utc, serde::ts_seconds};
use sea_orm::{
  ActiveValue, FromQueryResult, IntoActiveModel, Iterable, JoinType, QueryOrder, QuerySelect,
  entity::prelude::*,
};
use serde::{Deserialize, Serialize};

use super::{challenge, team, user};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "submission")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[serde(with = "ts_seconds")]
  pub created_at: DateTime<Utc>,
  pub user_id: i64,
  pub challenge_id: i64,
  pub team_id: Option<i64>,
  #[sea_orm(column_type = "Text")]
  pub content: Option<String>,
  pub solved: Option<bool>,
  #[sea_orm(column_type = "Text")]
  pub result: Option<String>,
}

impl Model {
  pub fn desensitize(self) -> Self {
    Self {
      content: None,
      ..self
    }
  }
}

#[derive(Clone, Debug, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
  pub id: i64,
  #[serde(with = "ts_seconds")]
  pub created_at: DateTime<Utc>,
  pub user_id: i64,
  pub user_name: Option<String>,
  pub challenge_id: i64,
  pub challenge_name: Option<String>,
  pub team_id: Option<i64>,
  pub team_name: Option<String>,
  pub content: Option<String>,
  pub solved: Option<bool>,
  pub score: i32,
  pub result: Option<String>,
}

impl ExModel {
  pub fn desensitize(self) -> Self {
    Self {
      content: None,
      ..self
    }
  }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::challenge::Entity",
    from = "Column::ChallengeId",
    to = "super::challenge::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Challenge,
  #[sea_orm(
    belongs_to = "super::team::Entity",
    from = "Column::TeamId",
    to = "super::team::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Team,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::UserId",
    to = "super::user::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::challenge::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Challenge.def()
  }
}

impl Related<super::team::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Team.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C, id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(id).one(db).await
}

#[allow(clippy::too_many_arguments)]
pub async fn get_page<C>(
  db: &C, page: u64, page_size: u64, only_solved: bool, with_content: bool, game_id: Option<i64>,
  challenge_id: Option<i64>, team_id: Option<i64>, user_id: Option<i64>,
) -> Result<(Vec<Model>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let mut sql = Entity::find().join(JoinType::InnerJoin, Relation::Challenge.def());
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
  }
  if !with_content {
    sql = sql
      .select_only()
      .columns(Column::iter().filter(|c| !matches!(c, Column::Content | Column::Result)));
  }
  let paginator = sql.into_model().paginate(db, page_size);
  let total = paginator.num_items().await?;
  let submissions = paginator.fetch_page(page - 1).await?;
  Ok((submissions, total))
}

#[allow(clippy::too_many_arguments)]
pub async fn get_list<C>(
  db: &C, only_solved: bool, with_content: bool, game_id: Option<i64>, challenge_id: Option<i64>,
  team_id: Option<i64>, user_id: Option<i64>, training: bool,
) -> Result<Vec<ExModel>, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Team.def())
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .join(JoinType::InnerJoin, Relation::User.def());
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
  }
  if !training && only_solved {
    sql = sql
      .filter(Column::TeamId.is_not_null())
      .filter(team::Column::State.gte(team::State::Hidden))
      .distinct_on([(Entity, Column::ChallengeId), (Entity, Column::TeamId)]);
  } else if only_solved {
    sql = sql.distinct_on([(Entity, Column::ChallengeId), (Entity, Column::UserId)]);
  }
  sql = sql.column_as(challenge::Column::Score, "score");

  let result = sql.into_model().all(db).await?;
  if !with_content {
    Ok(
      result
        .into_iter()
        .map(|r| ExModel {
          content: None,
          result: None,
          ..r
        })
        .collect(),
    )
  } else {
    Ok(result)
  }
}

#[allow(clippy::too_many_arguments)]
pub async fn get_list_ex<C>(
  db: &C, only_solved: bool, with_content: bool, game_id: Option<i64>, challenge_id: Option<i64>,
  team_id: Option<i64>, user_id: Option<i64>, training: bool,
) -> Result<Vec<ExModel>, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Team.def())
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .join(JoinType::InnerJoin, Relation::User.def())
    .column_as(user::Column::Nickname, "user_name")
    .column_as(team::Column::Name, "team_name")
    .column_as(challenge::Column::Name, "challenge_name");
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
  }
  if !training && only_solved {
    sql = sql
      .filter(Column::TeamId.is_not_null())
      .filter(team::Column::State.gte(team::State::Hidden))
      .distinct_on([(Entity, Column::ChallengeId), (Entity, Column::TeamId)]);
  } else if only_solved {
    sql = sql.distinct_on([(Entity, Column::ChallengeId), (Entity, Column::UserId)]);
  }
  sql = sql.column_as(challenge::Column::Score, "score");

  let result = sql.into_model().all(db).await?;
  if !with_content {
    Ok(
      result
        .into_iter()
        .map(|r| ExModel {
          content: None,
          result: None,
          ..r
        })
        .collect(),
    )
  } else {
    Ok(result)
  }
}

#[allow(clippy::too_many_arguments)]
pub async fn get_page_ex<C>(
  db: &C, page: u64, page_size: u64, only_solved: bool, with_content: bool, game_id: Option<i64>,
  challenge_id: Option<i64>, team_id: Option<i64>, user_id: Option<i64>,
) -> Result<(Vec<ExModel>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Team.def())
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .join(JoinType::InnerJoin, Relation::User.def())
    .column_as(user::Column::Nickname, "user_name")
    .column_as(team::Column::Name, "team_name")
    .column_as(challenge::Column::Name, "challenge_name");
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
  }
  sql = sql.column_as(challenge::Column::Score, "score");
  sql = sql.order_by_desc(Column::CreatedAt);
  let paginator = sql.into_model().paginate(db, page_size);
  let total = paginator.num_items().await?;
  let submissions = paginator.fetch_page(page - 1).await?;
  let submissions = if !with_content {
    submissions
      .into_iter()
      .map(|r| ExModel {
        content: None,
        result: None,
        ..r
      })
      .collect()
  } else {
    submissions
  };
  Ok((submissions, total))
}

#[allow(clippy::too_many_arguments)]
pub async fn count<C>(
  db: &C, only_solved: bool, game_id: Option<i64>, challenge_id: Option<i64>, team_id: Option<i64>,
  user_id: Option<i64>, institute_id: Option<i64>, training: bool,
) -> Result<u64, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Team.def())
    .join(JoinType::InnerJoin, Relation::Challenge.def());
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if let Some(institute_id) = institute_id {
    sql = sql.filter(team::Column::InstituteId.eq(institute_id));
  }
  if !training {
    sql = sql
      .filter(Column::TeamId.is_not_null())
      .filter(team::Column::State.gte(team::State::Hidden));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
    sql = sql.distinct_on([
      (Entity, Column::ChallengeId),
      (
        Entity,
        if !training {
          Column::TeamId
        } else {
          Column::UserId
        },
      ),
    ]);
  }
  sql.count(db).await
}

pub async fn create<C>(db: &C, submission: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let submission = ActiveModel {
    id: ActiveValue::NotSet,
    created_at: ActiveValue::Set(Utc::now()),
    ..submission.into_active_model().reset_all()
  };
  submission.insert(db).await
}

pub async fn update<C>(db: &C, submission: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let submission = ActiveModel {
    id: ActiveValue::Unchanged(submission.id),
    ..submission.into_active_model().reset_all()
  };
  submission.update(db).await
}

pub async fn delete<C>(db: &C, id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
