//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{DateTime, Utc, serde::ts_seconds};
use sea_orm::{
  ActiveValue, FromQueryResult, IntoActiveModel, Iterable, JoinType, QueryOrder, QuerySelect,
  entity::prelude::*,
};
use serde::{Deserialize, Serialize};

use super::{challenge, game, team, user};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "submission")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[serde(with = "ts_seconds")]
  pub created_at: DateTime<Utc>,
  pub user_id: i64,
  pub challenge_id: i64,
  pub team_id: Option<i64>,
  #[sea_orm(column_type = "Text")]
  pub content: Option<String>,
  pub solved: Option<bool>,
  #[sea_orm(column_type = "Text")]
  pub result: Option<String>,
}

impl Model {
  pub fn desensitize(self) -> Self {
    Self {
      content: None,
      ..self
    }
  }
}

#[derive(Clone, Debug, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
  pub id: i64,
  #[serde(with = "ts_seconds")]
  pub created_at: DateTime<Utc>,
  pub user_id: i64,
  pub user_name: Option<String>,
  pub challenge_id: i64,
  pub challenge_name: Option<String>,
  pub team_id: Option<i64>,
  pub team_name: Option<String>,
  pub content: Option<String>,
  pub solved: Option<bool>,
  pub score: i32,
  pub result: Option<String>,
}

impl ExModel {
  pub fn desensitize(self) -> Self {
    Self {
      content: None,
      ..self
    }
  }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::challenge::Entity",
    from = "Column::ChallengeId",
    to = "super::challenge::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Challenge,
  #[sea_orm(
    belongs_to = "super::team::Entity",
    from = "Column::TeamId",
    to = "super::team::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Team,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::UserId",
    to = "super::user::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::challenge::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Challenge.def()
  }
}

impl Related<super::team::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Team.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C, id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(id).one(db).await
}

#[allow(clippy::too_many_arguments)]
pub async fn get_page<C>(
  db: &C, page: u64, page_size: u64, only_solved: bool, with_content: bool, game_id: Option<i64>,
  challenge_id: Option<i64>, team_id: Option<i64>, user_id: Option<i64>,
) -> Result<(Vec<Model>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let mut sql = Entity::find().join(JoinType::InnerJoin, Relation::Challenge.def());
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
  }
  if !with_content {
    sql = sql
      .select_only()
      .columns(Column::iter().filter(|c| !matches!(c, Column::Content | Column::Result)));
  }
  let paginator = sql.into_model().paginate(db, page_size);
  let total = paginator.num_items().await?;
  let submissions = paginator.fetch_page(page - 1).await?;
  Ok((submissions, total))
}

#[allow(clippy::too_many_arguments)]
pub async fn get_list<C>(
  db: &C, only_solved: bool, with_content: bool, game_id: Option<i64>, challenge_id: Option<i64>,
  team_id: Option<i64>, user_id: Option<i64>, training: bool,
) -> Result<Vec<ExModel>, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Team.def())
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .join(JoinType::InnerJoin, Relation::User.def());
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
  }
  if !training && only_solved {
    sql = sql
      .filter(Column::TeamId.is_not_null())
      .filter(team::Column::State.gte(team::State::Hidden))
      .order_by_asc(Column::ChallengeId)
      .order_by_asc(Column::TeamId)
      .order_by_desc(Column::CreatedAt)
      .order_by_desc(Column::Id)
      .distinct_on([(Entity, Column::ChallengeId), (Entity, Column::TeamId)]);
  } else if only_solved {
    sql = sql
      .order_by_asc(Column::ChallengeId)
      .order_by_asc(Column::UserId)
      .order_by_desc(Column::CreatedAt)
      .order_by_desc(Column::Id)
      .distinct_on([(Entity, Column::ChallengeId), (Entity, Column::UserId)]);
  }
  sql = sql.column_as(challenge::Column::Score, "score");

  let result = sql.into_model().all(db).await?;
  if !with_content {
    Ok(
      result
        .into_iter()
        .map(|r| ExModel {
          content: None,
          result: None,
          ..r
        })
        .collect(),
    )
  } else {
    Ok(result)
  }
}

#[allow(clippy::too_many_arguments)]
pub async fn get_list_ex<C>(
  db: &C, only_solved: bool, with_content: bool, game_id: Option<i64>, challenge_id: Option<i64>,
  team_id: Option<i64>, user_id: Option<i64>, training: bool,
) -> Result<Vec<ExModel>, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Team.def())
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .join(JoinType::InnerJoin, Relation::User.def())
    .column_as(user::Column::Nickname, "user_name")
    .column_as(team::Column::Name, "team_name")
    .column_as(challenge::Column::Name, "challenge_name");
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
  }
  if !training && only_solved {
    sql = sql
      .filter(Column::TeamId.is_not_null())
      .filter(team::Column::State.gte(team::State::Hidden))
      .order_by_asc(Column::ChallengeId)
      .order_by_asc(Column::TeamId)
      .order_by_desc(Column::CreatedAt)
      .order_by_desc(Column::Id)
      .distinct_on([(Entity, Column::ChallengeId), (Entity, Column::TeamId)]);
  } else if only_solved {
    sql = sql
      .order_by_asc(Column::ChallengeId)
      .order_by_asc(Column::UserId)
      .order_by_desc(Column::CreatedAt)
      .order_by_desc(Column::Id)
      .distinct_on([(Entity, Column::ChallengeId), (Entity, Column::UserId)]);
  }
  sql = sql.column_as(challenge::Column::Score, "score");

  let result = sql.into_model().all(db).await?;
  if !with_content {
    Ok(
      result
        .into_iter()
        .map(|r| ExModel {
          content: None,
          result: None,
          ..r
        })
        .collect(),
    )
  } else {
    Ok(result)
  }
}

#[allow(clippy::too_many_arguments)]
pub async fn get_page_ex<C>(
  db: &C, page: u64, page_size: u64, only_solved: bool, with_content: bool, game_id: Option<i64>,
  challenge_id: Option<i64>, team_id: Option<i64>, user_id: Option<i64>,
) -> Result<(Vec<ExModel>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Team.def())
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .join(JoinType::InnerJoin, Relation::User.def())
    .column_as(user::Column::Nickname, "user_name")
    .column_as(team::Column::Name, "team_name")
    .column_as(challenge::Column::Name, "challenge_name");
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
  }
  sql = sql.column_as(challenge::Column::Score, "score");
  if only_solved {
    sql = sql
      .distinct_on([Column::ChallengeId, Column::TeamId, Column::UserId])
      .order_by_asc(Column::ChallengeId)
      .order_by_asc(Column::TeamId)
      .order_by_asc(Column::UserId)
      .order_by_asc(Column::CreatedAt)
      .order_by_asc(Column::Id);
  } else {
    sql = sql.order_by_desc(Column::CreatedAt);
  }
  let paginator = sql.into_model().paginate(db, page_size);
  let total = paginator.num_items().await?;
  let submissions = paginator.fetch_page(page - 1).await?;
  let submissions = if !with_content {
    submissions
      .into_iter()
      .map(|r| ExModel {
        content: None,
        result: None,
        ..r
      })
      .collect()
  } else {
    submissions
  };
  Ok((submissions, total))
}

#[derive(Debug, Serialize, FromQueryResult)]
pub struct ChallengeStat {
  pub challenge_id: i64,
  pub challenge_name: String,
  pub total: i64,
  pub solved: i64,
}

#[derive(Debug, Serialize, FromQueryResult)]
pub struct GameStat {
  pub game_id: i64,
  pub game_name: String,
  pub total: i64,
  pub solved: i64,
}

pub async fn get_user_challenge_stats<C>(
  db: &C, game_id: i64, user_id: i64,
) -> Result<Vec<ChallengeStat>, DbErr>
where
  C: ConnectionTrait, {
  #[derive(FromQueryResult)]
  struct ChallengeTotal {
    challenge_id: i64,
    challenge_name: String,
    total: i64,
  }

  #[derive(FromQueryResult)]
  struct ChallengeSolved {
    challenge_id: i64,
    solved: i64,
  }

  let totals = Entity::find()
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .filter(Column::UserId.eq(user_id))
    .filter(challenge::Column::GameId.eq(game_id))
    .select_only()
    .column_as(Column::ChallengeId, "challenge_id")
    .column_as(challenge::Column::Name, "challenge_name")
    .column_as(Column::Id.count(), "total")
    .group_by(Column::ChallengeId)
    .group_by(challenge::Column::Name)
    .order_by_asc(Column::ChallengeId)
    .into_model::<ChallengeTotal>()
    .all(db)
    .await?;

  let solved_rows = Entity::find()
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .filter(Column::UserId.eq(user_id))
    .filter(Column::Solved.eq(true))
    .filter(challenge::Column::GameId.eq(game_id))
    .select_only()
    .column_as(Column::ChallengeId, "challenge_id")
    .column_as(Column::Id.count(), "solved")
    .group_by(Column::ChallengeId)
    .into_model::<ChallengeSolved>()
    .all(db)
    .await?;

  let solved_map: std::collections::HashMap<i64, i64> = solved_rows
    .into_iter()
    .map(|r| (r.challenge_id, r.solved))
    .collect();

  let stats = totals
    .into_iter()
    .map(|t| ChallengeStat {
      challenge_id: t.challenge_id,
      challenge_name: t.challenge_name,
      total: t.total,
      solved: solved_map.get(&t.challenge_id).copied().unwrap_or(0),
    })
    .collect();

  Ok(stats)
}

pub async fn get_user_game_stats<C>(db: &C, user_id: i64) -> Result<Vec<GameStat>, DbErr>
where
  C: ConnectionTrait, {
  #[derive(FromQueryResult)]
  struct GameRow {
    game_id: i64,
    game_name: String,
    challenge_id: i64,
    solved: bool,
  }

  let rows = Entity::find()
    .join(JoinType::InnerJoin, Relation::Challenge.def())
    .join(JoinType::InnerJoin, challenge::Relation::Game.def())
    .filter(Column::UserId.eq(user_id))
    .select_only()
    .column_as(challenge::Column::GameId, "game_id")
    .column_as(game::Column::Name, "game_name")
    .column_as(Column::ChallengeId, "challenge_id")
    .column_as(Column::Solved, "solved")
    .into_model::<GameRow>()
    .all(db)
    .await?;

  use std::collections::{HashMap, HashSet};
  let mut game_challenges: HashMap<i64, (String, HashSet<i64>)> = HashMap::new();
  let mut game_solved: HashMap<i64, HashSet<i64>> = HashMap::new();

  for row in &rows {
    game_challenges
      .entry(row.game_id)
      .or_insert_with(|| (row.game_name.clone(), HashSet::new()))
      .1
      .insert(row.challenge_id);
    if row.solved {
      game_solved
        .entry(row.game_id)
        .or_default()
        .insert(row.challenge_id);
    }
  }

  let mut stats: Vec<GameStat> = game_challenges
    .into_iter()
    .map(|(game_id, (game_name, challenges))| GameStat {
      game_id,
      game_name,
      total: challenges.len() as i64,
      solved: game_solved
        .get(&game_id)
        .map(|s| s.len() as i64)
        .unwrap_or(0),
    })
    .collect();
  stats.sort_by_key(|g| g.game_id);
  Ok(stats)
}

#[allow(clippy::too_many_arguments)]
pub async fn count<C>(
  db: &C, only_solved: bool, game_id: Option<i64>, challenge_id: Option<i64>, team_id: Option<i64>,
  user_id: Option<i64>, institute_id: Option<i64>, training: bool,
) -> Result<u64, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Team.def())
    .join(JoinType::InnerJoin, Relation::Challenge.def());
  if let Some(game_id) = game_id {
    sql = sql.filter(challenge::Column::GameId.eq(game_id));
  }
  if let Some(challenge_id) = challenge_id {
    sql = sql.filter(Column::ChallengeId.eq(challenge_id));
  }
  if let Some(team_id) = team_id {
    sql = sql.filter(Column::TeamId.eq(team_id));
  }
  if let Some(user_id) = user_id {
    sql = sql.filter(Column::UserId.eq(user_id));
  }
  if let Some(institute_id) = institute_id {
    sql = sql.filter(team::Column::InstituteId.eq(institute_id));
  }
  if !training {
    sql = sql
      .filter(Column::TeamId.is_not_null())
      .filter(team::Column::State.gte(team::State::Hidden));
  }
  if only_solved {
    sql = sql.filter(Column::Solved.eq(true));
    sql = sql.distinct_on([
      (Entity, Column::ChallengeId),
      (
        Entity,
        if !training {
          Column::TeamId
        } else {
          Column::UserId
        },
      ),
    ]);
  }
  sql.count(db).await
}

pub async fn create<C>(db: &C, submission: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let submission = ActiveModel {
    id: ActiveValue::NotSet,
    created_at: ActiveValue::Set(Utc::now()),
    ..submission.into_active_model().reset_all()
  };
  submission.insert(db).await
}

pub async fn update<C>(db: &C, submission: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let submission = ActiveModel {
    id: ActiveValue::Unchanged(submission.id),
    ..submission.into_active_model().reset_all()
  };
  submission.update(db).await
}

pub async fn delete<C>(db: &C, id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
