//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{serde::ts_seconds, DateTime, Utc};
use sea_orm::{
    entity::prelude::*, ActiveValue, FromQueryResult, IntoActiveModel, Iterable, JoinType,
    QuerySelect,
};
use serde::{Deserialize, Serialize};

use super::{challenge, team, user};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "submission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(with = "ts_seconds")]
    pub created_at: DateTime<Utc>,
    pub user_id: i64,
    pub challenge_id: i64,
    pub team_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub content: Option<String>,
    pub solved: bool,
}

impl Model {
    pub fn desensitize(self) -> Self {
        Self {
            content: None,
            ..self
        }
    }
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
    pub id: i64,
    #[serde(with = "ts_seconds")]
    pub created_at: DateTime<Utc>,
    pub user_id: i64,
    pub user_name: String,
    pub challenge_id: i64,
    pub challenge_name: String,
    pub team_id: Option<i64>,
    pub team_name: Option<String>,
    pub content: Option<String>,
    pub solved: bool,
}

impl ExModel {
    pub fn desensitize(self) -> Self {
        Self {
            content: None,
            ..self
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::challenge::Entity",
        from = "Column::ChallengeId",
        to = "super::challenge::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Challenge,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Team,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get_page(
    db: &DatabaseConnection, page: u64, page_size: u64, only_solved: bool, with_content: bool,
    challenge_id: Option<i64>, team_id: Option<i64>, user_id: Option<i64>,
) -> Result<(Vec<Model>, u64), DbErr> {
    let mut sql = Entity::find();
    if let Some(challenge_id) = challenge_id {
        sql = sql.filter(Column::ChallengeId.eq(challenge_id));
    }
    if let Some(team_id) = team_id {
        sql = sql.filter(Column::TeamId.eq(team_id));
    }
    if let Some(user_id) = user_id {
        sql = sql.filter(Column::UserId.eq(user_id));
    }
    if only_solved {
        sql = sql.filter(Column::Solved.eq(true));
    }
    if !with_content {
        sql = sql
            .select_only()
            .columns(Column::iter().filter(|c| !matches!(c, Column::Content)));
    }
    let paginator = sql.into_model().paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let submissions = paginator.fetch_page(page - 1).await?;
    Ok((submissions, total))
}

pub async fn get_page_ex(
    db: &DatabaseConnection, page: u64, page_size: u64, only_solved: bool, with_content: bool,
    challenge_id: Option<i64>, team_id: Option<i64>, user_id: Option<i64>,
) -> Result<(Vec<ExModel>, u64), DbErr> {
    let mut sql = Entity::find()
        .join(JoinType::InnerJoin, Relation::Team.def())
        .join(JoinType::InnerJoin, Relation::Challenge.def())
        .join(JoinType::InnerJoin, Relation::User.def())
        .column_as(user::Column::Nickname, "user_name")
        .column_as(team::Column::Name, "team_name")
        .column_as(challenge::Column::Name, "challenge_name");
    if let Some(challenge_id) = challenge_id {
        sql = sql.filter(Column::ChallengeId.eq(challenge_id));
    }
    if let Some(team_id) = team_id {
        sql = sql.filter(Column::TeamId.eq(team_id));
    }
    if let Some(user_id) = user_id {
        sql = sql.filter(Column::UserId.eq(user_id));
    }
    if only_solved {
        sql = sql.filter(Column::Solved.eq(true));
    }
    if !with_content {
        sql = sql
            .select_only()
            .columns(Column::iter().filter(|c| !matches!(c, Column::Content)));
    }
    let paginator = sql.into_model().paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let submissions = paginator.fetch_page(page - 1).await?;
    Ok((submissions, total))
}

pub async fn create(db: &DatabaseConnection, submission: Model) -> Result<Model, DbErr> {
    let submission = ActiveModel {
        id: ActiveValue::NotSet,
        created_at: ActiveValue::Set(Utc::now()),
        ..submission.into_active_model().reset_all()
    };
    submission.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
