//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use std::str::FromStr;

use chrono::{DateTime, Utc, serde::ts_seconds};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{
  ActiveValue, Condition, FromJsonQueryResult, FromQueryResult, IntoActiveModel, Iterable,
  JoinType, Order, QueryOrder, QuerySelect, entity::prelude::*,
};
use sea_query::Func;
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use super::user;
use crate::{game, institute, user2_team};

#[derive(
  Clone,
  Debug,
  Default,
  PartialEq,
  Eq,
  PartialOrd,
  Serialize_repr,
  Deserialize_repr,
  EnumIter,
  DeriveActiveEnum,
  FromPrimitive,
  ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum State {
  Banned  = 0,
  #[default]
  Pending = 1,
  Hidden  = 2,
  Passed  = 3,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistory {
  pub score: i32,
  #[serde(with = "ts_seconds")]
  pub changed_at: DateTime<Utc>,
  pub challenge_id: Option<i64>,
  pub blood_state: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistoryList(pub Vec<TeamScoreHistory>);

impl TeamScoreHistoryList {
  pub fn new() -> Self {
    Self(vec![TeamScoreHistory {
      changed_at: Utc::now(),
      ..Default::default()
    }])
  }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "team")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub name: String,
  pub game_id: i64,
  pub token: Option<String>,
  pub state: State,
  pub institute_id: Option<i64>,
  pub score: i32,
  #[sea_orm(column_type = "JsonBinary")]
  pub history: TeamScoreHistoryList,
  #[serde(with = "ts_seconds")]
  pub last_active_at: DateTime<Utc>,
  pub tag: Option<String>,
}

impl Model {
  pub fn desensitize(self) -> Self {
    Self {
      token: None,
      ..self
    }
  }
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
  pub id: i64,
  pub name: String,
  pub game_id: i64,
  pub game_name: Option<String>,
  pub token: Option<String>,
  pub state: State,
  pub institute_id: Option<i64>,
  pub institute_name: Option<String>,
  pub score: i32,
  pub history: TeamScoreHistoryList,
  #[serde(with = "ts_seconds")]
  pub last_active_at: DateTime<Utc>,
  pub tag: Option<String>,
}

impl ExModel {
  pub fn desensitize(self) -> Self {
    Self {
      token: None,
      ..self
    }
  }
}

impl From<Model> for ExModel {
  fn from(model: Model) -> Self {
    ExModel {
      id: model.id,
      name: model.name,
      game_id: model.game_id,
      game_name: None,
      token: model.token,
      state: model.state,
      institute_id: model.institute_id,
      institute_name: None,
      score: model.score,
      history: model.history,
      last_active_at: model.last_active_at,
      tag: model.tag,
    }
  }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::audit::Entity")]
  Audit,
  #[sea_orm(has_many = "super::extra::Entity")]
  Extra,
  #[sea_orm(
    belongs_to = "super::game::Entity",
    from = "Column::GameId",
    to = "super::game::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Game,
  #[sea_orm(
    belongs_to = "super::institute::Entity",
    from = "Column::InstituteId",
    to = "super::institute::Column::Id",
    on_update = "Cascade",
    on_delete = "SetNull"
  )]
  Institute,
  #[sea_orm(has_many = "super::submission::Entity")]
  Submission,
  #[sea_orm(has_many = "super::user2_team::Entity")]
  User2Team,
}

impl Related<super::audit::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Audit.def()
  }
}

impl Related<super::extra::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Extra.def()
  }
}

impl Related<super::game::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Game.def()
  }
}

impl Related<super::institute::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Institute.def()
  }
}

impl Related<super::submission::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Submission.def()
  }
}

impl Related<super::user2_team::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User2Team.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    super::user2_team::Relation::User.def()
  }
  fn via() -> Option<RelationDef> {
    Some(super::user2_team::Relation::User.def().rev())
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get<C>(db: &C, id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(id).one(db).await
}

pub async fn get_ex<C>(db: &C, id: i64) -> Result<Option<ExModel>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find_by_id(id)
    .join(JoinType::LeftJoin, Relation::Institute.def())
    .join(JoinType::InnerJoin, Relation::Game.def())
    .column_as(game::Column::Name, "game_name")
    .column_as(institute::Column::Name, "institute_name")
    .into_model()
    .one(db)
    .await
}

pub async fn get_by_token<C>(db: &C, game_id: i64, token: &str) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  Entity::find()
    .filter(Column::GameId.eq(game_id))
    .filter(Column::Token.eq(token))
    .one(db)
    .await
}

pub async fn get_by_user_id<C>(db: &C, game_id: i64, user_id: i64) -> Result<Option<Model>, DbErr>
where
  C: ConnectionTrait, {
  let (_, team): (user::Model, Option<Model>) = match user::Entity::find_by_id(user_id)
    .find_also_related(Entity)
    .filter(Column::GameId.eq(game_id))
    .one(db)
    .await?
  {
    Some((user, team)) => (user, team),
    None => {
      return Ok(None);
    }
  };
  Ok(team)
}

pub async fn get_list_by_user_id<C>(db: &C, user_id: i64) -> Result<Vec<Model>, DbErr>
where
  C: ConnectionTrait, {
  user2_team::Entity::find()
    .filter(user2_team::Column::UserId.eq(user_id))
    .join(JoinType::InnerJoin, user2_team::Relation::Team.def())
    .into_model()
    .all(db)
    .await
}

pub async fn get_list_by_user_id_ex<C>(db: &C, user_id: i64) -> Result<Vec<ExModel>, DbErr>
where
  C: ConnectionTrait, {
  user2_team::Entity::find()
    .select_only()
    .columns(Column::iter().filter(|c| !matches!(c, Column::Token)))
    .filter(user2_team::Column::UserId.eq(user_id))
    .join(JoinType::LeftJoin, user2_team::Relation::Team.def())
    .join(JoinType::LeftJoin, Relation::Institute.def())
    .join(JoinType::LeftJoin, Relation::Game.def())
    .column_as(institute::Column::Name, "institute_name")
    .column_as(game::Column::Name, "game_name")
    .into_model()
    .all(db)
    .await
}

pub async fn get_members<C>(db: &C, id: i64) -> Result<Vec<user::Model>, DbErr>
where
  C: ConnectionTrait, {
  user2_team::Entity::find()
    .filter(user2_team::Column::TeamId.eq(id))
    .select_only()
    .columns(user::Column::iter())
    .join(JoinType::InnerJoin, user2_team::Relation::User.def())
    .into_model()
    .all(db)
    .await
}

#[allow(clippy::too_many_arguments)]
pub async fn get_page<C>(
  db: &C, game_id: i64, page: u64, page_size: u64, min_state: Option<State>,
  institute_id: Option<i64>, filter: Option<String>, order_by: Option<String>, asc: bool,
) -> Result<(Vec<Model>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let state = min_state.unwrap_or(State::Passed);
  let mut sql = Entity::find()
    .filter(Column::GameId.eq(game_id))
    .filter(Column::State.gte(state));
  sql = filter_sql(sql, filter)?;
  if let Some(institute_id) = institute_id {
    sql = sql.filter(Column::InstituteId.eq(institute_id));
  }
  if let Some(order_by) = order_by {
    let order_by = Column::from_str(order_by.as_str())
      .map_err(|e| DbErr::Custom(format!("invalid order_by: {e}")))?;
    sql = if asc {
      sql.order_by(order_by, Order::Asc)
    } else {
      sql.order_by(order_by, Order::Desc)
    };
  }
  sql = sql.order_by(Column::LastActiveAt, Order::Asc);
  let paginator = sql.into_model().paginate(db, page_size);
  let total = paginator.num_items().await?;
  let teams = paginator.fetch_page(page - 1).await?;
  Ok((teams, total))
}

#[allow(clippy::too_many_arguments)]
pub async fn get_page_ex<C>(
  db: &C, game_id: i64, page: u64, page_size: u64, min_state: Option<State>,
  institute_id: Option<i64>, filter: Option<String>, order_by: Option<String>, asc: bool,
) -> Result<(Vec<ExModel>, u64), DbErr>
where
  C: ConnectionTrait, {
  let page_size = page_size.max(1);
  let page = page.max(1);
  let state = min_state.unwrap_or(State::Passed);
  let mut sql = Entity::find()
    .join(JoinType::LeftJoin, Relation::Institute.def())
    .join(JoinType::LeftJoin, Relation::Game.def())
    .column_as(institute::Column::Name, "institute_name")
    .column_as(game::Column::Name, "game_name")
    .filter(Column::GameId.eq(game_id))
    .filter(Column::State.gte(state));
  sql = filter_sql(sql, filter)?;
  if let Some(institute_id) = institute_id {
    sql = sql.filter(Column::InstituteId.eq(institute_id));
  }
  if let Some(order_by) = order_by {
    let order_by = Column::from_str(order_by.as_str())
      .map_err(|e| DbErr::Custom(format!("invalid order_by: {e}")))?;
    sql = if asc {
      sql.order_by(order_by, Order::Asc)
    } else {
      sql.order_by(order_by, Order::Desc)
    };
  }
  sql = sql.order_by(Column::LastActiveAt, Order::Asc);
  let paginator = sql.into_model().paginate(db, page_size);
  let total = paginator.num_items().await?;
  let teams = paginator.fetch_page(page - 1).await?;
  Ok((teams, total))
}

fn filter_sql(mut sql: Select<Entity>, filter: Option<String>) -> Result<Select<Entity>, DbErr> {
  if let Some(filter) = filter {
    let mut cond = Condition::any();
    if let Ok(num) = filter.parse::<i64>() {
      cond = cond.add(Column::Id.eq(num));
      cond = cond.add(Column::State.eq(num));
    }
    let filter = format!("%{}%", filter.to_ascii_lowercase());
    cond = cond.add(Expr::expr(Func::lower(Expr::col(Column::Name))).like(filter.clone()));
    cond = cond.add(Column::Token.like(filter.clone()));
    sql = sql.filter(cond);
  };
  Ok(sql)
}

pub async fn count<C>(
  db: &C, game_id: i64, min_state: State, institute_id: Option<i64>,
) -> Result<u64, DbErr>
where
  C: ConnectionTrait, {
  let mut sql = Entity::find()
    .filter(Column::GameId.eq(game_id))
    .filter(Column::State.gte(min_state));
  if let Some(institute_id) = institute_id {
    sql = sql.filter(Column::InstituteId.eq(institute_id));
  }
  sql.count(db).await
}

pub async fn create<C>(db: &C, team: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let team = ActiveModel {
    id: ActiveValue::NotSet,
    last_active_at: ActiveValue::Set(Utc::now()),
    history: ActiveValue::Set(TeamScoreHistoryList::new()),
    ..team.into_active_model().reset_all()
  };
  team.insert(db).await
}

pub async fn update<C>(db: &C, team: Model) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let team = ActiveModel {
    id: ActiveValue::Unchanged(team.id),
    game_id: ActiveValue::Unchanged(team.game_id),
    ..team.into_active_model().reset_all()
  };
  team.update(db).await
}

pub async fn delete<C>(db: &C, id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_by_id(id).exec(db).await.map(|_| ())
}

pub async fn calc_score<C>(db: &C, id: i64) -> Result<i32, DbErr>
where
  C: ConnectionTrait, {
  let solves =
    super::submission::get_list(db, true, false, None, None, Some(id), None, false).await?;
  let score: i32 = solves.iter().map(|s| s.score).sum();
  let extras = super::extra::get_list(db, id).await?;
  let extra_score: i32 = extras.iter().map(|e| e.score).sum();
  let total = score + extra_score;
  Ok(total)
}

pub async fn count_rank<C>(
  db: &C, game_id: i64, score: i32, last_active_at: DateTime<Utc>, with_hidden: bool,
) -> Result<i64, DbErr>
where
  C: ConnectionTrait, {
  let count = Entity::find()
    .filter(Column::GameId.eq(game_id))
    .filter(Column::State.gte(if with_hidden {
      State::Hidden
    } else {
      State::Passed
    }))
    .filter(
      Condition::any().add(Column::Score.gt(score)).add(
        Condition::all()
          .add(Column::Score.eq(score))
          .add(Column::LastActiveAt.lt(last_active_at)),
      ),
    )
    .count(db)
    .await?;
  Ok(count as i64 + 1)
}
