//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{serde::ts_seconds, DateTime, Utc};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{
    entity::prelude::*, ActiveValue, Condition, FromJsonQueryResult, FromQueryResult,
    IntoActiveModel,
};
use sea_query::Func;
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

use super::user;

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum State {
    Banned  = 0,
    #[default]
    Pending = 1,
    Hidden  = 2,
    Passed  = 3,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistory {
    pub score: i32,
    #[serde(with = "ts_seconds")]
    pub changed_at: DateTime<Utc>,
    pub challenge_id: Option<i64>,
    pub blood_state: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistoryList(pub Vec<TeamScoreHistory>);

impl TeamScoreHistoryList {
    pub fn new() -> Self {
        Self(vec![TeamScoreHistory {
            changed_at: Utc::now(),
            ..Default::default()
        }])
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub game_id: i64,
    pub token: Option<String>,
    pub state: State,
    pub institute_id: Option<i64>,
    pub score: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub history: TeamScoreHistoryList,
    #[serde(with = "ts_seconds")]
    pub last_active_at: DateTime<Utc>,
}

impl Model {
    pub fn desensitize(self) -> Self {
        Self {
            token: None,
            ..self
        }
    }
}

#[derive(Clone, Serialize, Deserialize, FromQueryResult)]
pub struct ExModel {
    pub id: i64,
    pub name: String,
    pub game_id: i64,
    pub token: Option<String>,
    pub state: State,
    pub institute_id: Option<i64>,
    pub institute_name: Option<String>,
    pub score: i32,
    pub history: TeamScoreHistoryList,
    #[serde(with = "ts_seconds")]
    pub last_active_at: DateTime<Utc>,
}

impl ExModel {
    pub fn desensitize(self) -> Self {
        Self {
            token: None,
            ..self
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit::Entity")]
    Audit,
    #[sea_orm(has_many = "super::extra::Entity")]
    Extra,
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Institute,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
    #[sea_orm(has_many = "super::user2_team::Entity")]
    User2Team,
}

impl Related<super::audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Audit.def()
    }
}

impl Related<super::extra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extra.def()
    }
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<super::user2_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Team.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_team::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_team::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(db: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(id).one(db).await
}

pub async fn get_by_user_id(
    db: &DatabaseConnection, game_id: i64, user_id: i64,
) -> Result<Option<Model>, DbErr> {
    let (_, team): (user::Model, Option<Model>) = match user::Entity::find_by_id(user_id)
        .find_also_related(Entity)
        .filter(Column::GameId.eq(game_id))
        .one(db)
        .await?
    {
        Some((user, team)) => (user, team),
        None => {
            return Ok(None);
        }
    };
    Ok(team)
}

pub async fn get_page(
    db: &DatabaseConnection, game_id: i64, page: u64, page_size: u64, min_state: Option<State>,
    filter: Option<String>,
) -> Result<(Vec<Model>, u64), DbErr> {
    let state = min_state.unwrap_or(State::Passed);
    let mut sql = Entity::find()
        .filter(Column::GameId.eq(game_id))
        .filter(Column::State.gte(state));
    sql = filter_sql(sql, filter)?;
    let paginator = sql.into_model().paginate(db, page_size);
    let total = paginator.num_pages().await?;
    let teams = paginator.fetch_page(page - 1).await?;
    Ok((teams, total))
}

fn filter_sql(mut sql: Select<Entity>, filter: Option<String>) -> Result<Select<Entity>, DbErr> {
    if let Some(filter) = filter {
        let mut cond = Condition::any();
        if let Ok(num) = filter.parse::<i64>() {
            cond = cond.add(Column::Id.eq(num));
            cond = cond.add(Column::State.eq(num));
        }
        let filter = format!("%{}%", filter.to_ascii_lowercase());
        cond = cond.add(Expr::expr(Func::lower(Expr::col(Column::Name))).like(filter.clone()));
        sql = sql.filter(cond);
    };
    Ok(sql)
}

pub async fn create(db: &DatabaseConnection, team: Model) -> Result<Model, DbErr> {
    let team = ActiveModel {
        id: ActiveValue::NotSet,
        last_active_at: ActiveValue::Set(Utc::now()),
        history: ActiveValue::Set(TeamScoreHistoryList::new()),
        ..team.into_active_model().reset_all()
    };
    team.insert(db).await
}

pub async fn update(db: &DatabaseConnection, team: Model) -> Result<Model, DbErr> {
    let team = ActiveModel {
        id: ActiveValue::Unchanged(team.id),
        game_id: ActiveValue::Unchanged(team.game_id),
        ..team.into_active_model().reset_all()
    };
    team.insert(db).await
}

pub async fn delete(db: &DatabaseConnection, id: i64) -> Result<(), DbErr> {
    Entity::delete_by_id(id).exec(db).await.map(|_| ())
}
