//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{
    serde::ts_seconds::{deserialize as from_ts, serialize as to_ts},
    DateTime, Utc,
};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(
    Clone,
    Debug,
    Default,
    PartialEq,
    Eq,
    PartialOrd,
    Serialize_repr,
    Deserialize_repr,
    EnumIter,
    DeriveActiveEnum,
    FromPrimitive,
    ToPrimitive,
)]
#[repr(i32)]
#[sea_orm(rs_type = "i32", db_type = "Integer")]
pub enum State {
    Banned = 0,
    #[default]
    Pending = 1,
    Passed = 2,
    Hidden = 3,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistory {
    pub score: i32,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub time: DateTime<Utc>,
    pub challenge_id: Option<i64>,
    pub blood_state: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct TeamScoreHistoryList(pub Vec<TeamScoreHistory>);

impl TeamScoreHistoryList {
    pub fn new() -> Self {
        Self(vec![TeamScoreHistory {
            time: Utc::now(),
            ..Default::default()
        }])
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub game_id: i64,
    pub token: Option<String>,
    pub state: State,
    pub institute_id: Option<i64>,
    pub score: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub history: TeamScoreHistoryList,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub last_active_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit::Entity")]
    Audit,
    #[sea_orm(has_many = "super::extra::Entity")]
    Extra,
    #[sea_orm(
        belongs_to = "super::game::Entity",
        from = "Column::GameId",
        to = "super::game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Game,
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Institute,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
    #[sea_orm(has_many = "super::user2_team::Entity")]
    User2Team,
}

impl Related<super::audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Audit.def()
    }
}

impl Related<super::extra::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extra.def()
    }
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<super::user2_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Team.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_team::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_team::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(db: &DatabaseConnection, id: i64) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(id).one(db).await
}
