//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::{ActiveValue, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user2_team")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub user_id: i64,
  pub team_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::team::Entity",
    from = "Column::TeamId",
    to = "super::team::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  Team,
  #[sea_orm(
    belongs_to = "super::user::Entity",
    from = "Column::UserId",
    to = "super::user::Column::Id",
    on_update = "Cascade",
    on_delete = "Cascade"
  )]
  User,
}

impl Related<super::team::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Team.def()
  }
}

impl Related<super::user::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::User.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}

pub async fn user_join_team<C>(db: &C, user_id: i64, team_id: i64) -> Result<Model, DbErr>
where
  C: ConnectionTrait, {
  let model = ActiveModel {
    id: ActiveValue::NotSet,
    user_id: ActiveValue::Set(user_id),
    team_id: ActiveValue::Set(team_id),
  };
  model.insert(db).await
}

pub async fn user_leave_team<C>(db: &C, user_id: i64, team_id: i64) -> Result<(), DbErr>
where
  C: ConnectionTrait, {
  Entity::delete_many()
    .filter(Column::UserId.eq(user_id))
    .filter(Column::TeamId.eq(team_id))
    .exec(db)
    .await
    .map(|_| ())
}
