version: '3'

services:
  platform:
    image: ret2shell:latest
    build: ./server
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ret2shell:/var/lib/ret2shell
      - ./config:/etc/ret2shell:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # - /$XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock
    networks:
      default:
      internal:
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: <replace_me>
      POSTGRES_USER: ret2shell
      POSTGRES_DB: ret2shell
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      internal:
  cache:
    image: valkey/valkey:7-alpine
    restart: always
    volumes:
      - cache:/data
    networks:
      internal:
  message_queue:
    image: nats:2-alpine
    restart: always
    volumes:
      - message_queue:/data
    command: ["-js", "-sd", "/data"]
    networks:
      internal:

volumes:
  ret2shell:
  database:
  cache:
  message_queue:

networks:
  default:
  internal:
    internal: true
