[auditor]
sensitive_word_list = './config/sensitive_word_list.txt'

[auth]
signing_key = '857f1cda-01f7-473c-b957-6d4744230a47'
buffer_time = 21600
expires_time = 86400

[automate]
enabled = false
token = 'T0k3nInD3v3l0pm3nt'

[bucket]
path = './data/bucket'

[cache]
# Cluster supports here.
# redis://username:password@foo.com:6379/1
# rediss://username:password@foo.com:6379/1
# redis-cluster://username:password@foo.com:30001?node=bar.com:30002&node=baz.com:30003
# redis-sentinel://username:password@foo.com:6379/1?sentinelServiceName=fakename&node=foo.com:30001&node=bar.com:30002
url = 'redis://localhost:6379'

[captcha]
enabled = true
difficulty = 4
validator = 'Pow'

[cluster]
try_default = false
auto_infer = true
kube_config_path = "~/.kube/config"
challenge_node_selector = "challenge"
proxy_image = "ret2shell/container-proxy:main"

[database]
db = 'ret2shell'
host = '127.0.0.1'
port = 5432
user = 'ret2shell'
password = 'P@ssw02dInD3v3l0pm3nt'
ssl_mode = 'disable'               # disable, allow, prefer, require, verify-ca, verify-full

[email]
enabled = false
host = 'smtp.example.com'
port = 587
sender = 'Ret2Shell'
username = 'ret2shell@woooo.tech'
password = 'P@ssw0rdInD3v3l0pm3nt'
tls = 'starttls'                   #  'none' | 'tls' | 'starttls'

[logging]
directory = './data/log'
level = 'info,tower_http=info,sqlx=warn'

[media]
path = './data/media'

[queue]
host = '127.0.0.1'
port = 4222
### token has higher priority than user & password, only one auth method will be used.
#token = 'T0k3nInD3v3l0pm3nt'
### user and password must be both valid, whether it will be ignored.
#user = 'ret2shell'
#password = 'P@ssw0rdInD3v3l0pm3nt'
#ping_interval = 5
#tls = false

[server]
host = '127.0.0.1'
port = 8080
external_domain = 'ctf.woooo.tech'
external_https = true
api_base_path = '/api'
cors_origins = '*'
init_token = 'Samp1eT0k3n'
