name = "Example Game"
brief = "Example Game brief"
register_at = 1713630259
start_at = 1713630263
end_at = 1713630266
archive_at = 1713630268
team_size = 1
host_type = 1                     # CTFTraining: 0, CTFGame: 1
cover = "./cover.webp"
logo = "./logo.svg"
can_register_after_started = true
award_rate = 5
weight = 3

[access_policy]
sync = 0
