//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub updated_at: DateTimeWithTimeZone,
    pub name: String,
    pub brief: String,
    pub introduction_id: i64,
    pub start_at: DateTimeWithTimeZone,
    pub end_at: DateTimeWithTimeZone,
    pub register_at: DateTimeWithTimeZone,
    pub archive_at: DateTimeWithTimeZone,
    pub hidden: bool,
    pub offline: bool,
    pub frozen: bool,
    pub host_type: i32,
    pub team_size: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub access_policy: Json,
    pub cover: Option<String>,
    pub logo: Option<String>,
    pub enable_audit: bool,
    pub can_register_after_started: bool,
    pub award_rate: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::article::Entity",
        from = "Column::IntroductionId",
        to = "super::article::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Introduction,
    #[sea_orm(has_many = "super::challenge::Entity")]
    Challenge,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::team::Entity")]
    Team,
}

impl Related<super::article::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Introduction.def()
    }
}

impl Related<super::challenge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Challenge.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
