//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod article;
pub mod article_closure;
pub mod audit;
pub mod calendar;
pub mod challenge;
pub mod comment;
pub mod comment_closure;
pub mod config;
pub mod extra;
pub mod game;
pub mod hint;
pub mod instance;
pub mod institute;
pub mod ip;
pub mod media;
pub mod notification;
pub mod oauth;
pub mod policy;
pub mod submission;
pub mod team;
pub mod user;
pub mod user2_ip;
pub mod user2_team;
