//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use chrono::{
    serde::ts_seconds::{deserialize as from_ts, serialize as to_ts},
    DateTime, Utc,
};
use num_derive::{FromPrimitive, ToPrimitive};
use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};

#[derive(
    FromPrimitive, ToPrimitive, Clone, Copy, Debug, PartialEq, Serialize_repr, Deserialize_repr, Eq,
)]
#[repr(i32)]
pub enum Permission {
    Basic,
    Verified,
    Calendar,
    Wiki,
    Bulletin,
    Game,
    Host,
    User,
    Statistics,
    DevOps,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Permissions(pub Vec<Permission>);

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[serde(deserialize_with = "from_ts", serialize_with = "to_ts")]
    pub registered_at: DateTime<Utc>,
    #[sea_orm(unique)]
    pub account: String,
    pub nickname: String,
    pub password: String,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub avatar: Option<String>,
    pub institute_id: Option<i64>,
    #[sea_orm(column_type = "JsonBinary")]
    pub permissions: Permissions,
    pub hidden: bool,
    pub banned: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article::Entity")]
    Article,
    #[sea_orm(has_many = "super::audit::Entity")]
    Audit,
    #[sea_orm(has_many = "super::calendar::Entity")]
    Calendar,
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
    #[sea_orm(
        belongs_to = "super::institute::Entity",
        from = "Column::InstituteId",
        to = "super::institute::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Institute,
    #[sea_orm(has_many = "super::media::Entity")]
    Media,
    #[sea_orm(has_many = "super::oauth::Entity")]
    Oauth,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
    #[sea_orm(has_many = "super::user2_ip::Entity")]
    User2Ip,
    #[sea_orm(has_many = "super::user2_team::Entity")]
    User2Team,
}

impl Related<super::article::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Article.def()
    }
}

impl Related<super::audit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Audit.def()
    }
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl Related<super::institute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institute.def()
    }
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::oauth::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Oauth.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<super::user2_ip::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Ip.def()
    }
}

impl Related<super::ip::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_ip::Relation::Ip.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_ip::Relation::User.def().rev())
    }
}

impl Related<super::user2_team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User2Team.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        super::user2_team::Relation::Team.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user2_team::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
