apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ret2shell.fullname" . }}
  labels:
    {{- include "ret2shell.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ret2shell.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ret2shell.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ret2shell.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/ret2shell
            - name: config
              mountPath: /etc/ret2shell/config.toml
              subPath: config.toml
              readOnly: true
            - name: license
              mountPath: /etc/ret2shell/license
              subPath: license
              readOnly: true
            - name: sensitive-words
              mountPath: /etc/ret2shell/sensitive_word_list.txt
              subPath: sensitive_word_list.txt
              readOnly: true
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "ret2shell.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config
          configMap:
            name: {{ default (printf "%s-config" (include "ret2shell.fullname" .)) .Values.config.existingConfigMap }}
            items:
              - key: config.toml
                path: config.toml
        - name: sensitive-words
          configMap:
            name: {{ default (printf "%s-sensitive" (include "ret2shell.fullname" .)) .Values.sensitiveWords.existingConfigMap }}
            items:
              - key: sensitive_word_list.txt
                path: sensitive_word_list.txt
        - name: license
          secret:
            secretName: {{ default (printf "%s-license" (include "ret2shell.fullname" .)) .Values.license.existingSecret }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
